### ISSUE TITLE
overplot times of an event at top/bottom of time series plot

### ISSUE THREAD

**Issue by kenkehoe** [ARM-DOE/ACT#125]
I think we need a way to overplot a status onto a time series plot. For example when a sensor is tripped (e.g. MWR rain flag), when rain is detected by another instrument (i.e. MET TBRG) or when some state is happening with the data (i.e. a fan is running indicated by a variable being over a threshold).

My plan is to add a bar or something like that to an existing plot. But instead of adding this feature to the existing plot definition, I'm thinking of a new method to add to an existing plot. This may be better for cases when we want to add information from a different instrument (object) without adding to the primary object used for plotting. 

You can assign this issue to me.

**Comment by AdamTheisen** [comment]
@kenkehoe I was going to try some tests on this. I wonder if there is an easier way than a new method

**Comment by AdamTheisen** [comment]
What do you think of this as an option?  It's just 2 additional lines.  Getting the index and then the plot call.

`index = np.where(met_temp < -2.)[0]
....
#Display data using plotting methods
new = {'sgpmetE13.b1': met, 'sgpceilC1.b1':ceil}
display = act.plotting.TimeSeriesDisplay(new,figsize=(8,5))
display.plot('met_lcl',dsname='sgpmetE13.b1',color='b')
display.day_night_background('sgpmetE13.b1')
set_title = ' '.join(['MET LCL and CEIL CBH on',
act.utils.datetime_utils.numpy_to_arm_date(met.time.values[0])])
display.plot('first_cbh',dsname='sgpceilC1.b1',color='g',set_title=set_title)
display.set_yrng([0,7500])
**display.axes[0].plot(met['time'].values[index], np.full(len(index), display.axes[0].get_ylim()[0]), '|r')**
display.axes[0].legend()
plt.savefig('./images/lcl.png')
plt.clf()
`
![lcl](https://user-images.githubusercontent.com/13421074/65518233-97da0d80-dea9-11e9-9759-f74a5fb3c7c3.png)

**Comment by kenkehoe** [comment]
OK that is a good solution. I'll think about this.

**Comment by AdamTheisen** [comment]
@kenkehoe have you had a chance to think about this implementation?

**Comment by kenkehoe** [comment]
Yeah, I've implemented something similar to your code snippet above a few times. Since this is just a few lines of extra code outside of ACT I think we can skip adding more code to ACT. We can close this.

**Comment by kenkehoe** [comment]
Since we have a solution outside of ACT I'm going to close this.
