### ISSUE TITLE
geodisplay.py projection not working with any other options but the default

### ISSUE THREAD

**Issue by jhemedin** [ARM-DOE/ACT#160]
While using the GeographicPlotDisplay function when trying to use other cartopy projections the map extent changes or no data appears. 

The default is PlateCarree and works fine but when trying to use a Mercator projection the data shows up but the map extent is changed. 
![image](https://user-images.githubusercontent.com/21142062/71207275-1e657780-226c-11ea-9727-05912f50922c.png)

When using a LambertConformal projection the extent appears to be off since no features appear that were suppose to be plotted.
![image](https://user-images.githubusercontent.com/21142062/71207609-ddba2e00-226c-11ea-95d6-6df6f5b587ef.png)

**Comment by kenkehoe** [comment]
According to error when running projection=ccrs.LambertConformal():

"TypeError: Cannot label gridlines on a LambertConformal plot.  Only PlateCarree and Mercator plots are currently supported."

I've updated the code to only attempt to add labels to PlateCarree and Mercator, but still add gridlines. It's still not doing what I would want. We may need to look elsewhere for a plotting library.

LambertConformal:
![LambertConformal](https://user-images.githubusercontent.com/8261054/83295515-53c3a900-a1ac-11ea-9414-04d61130d930.png)

Mercator:
![Mercator](https://user-images.githubusercontent.com/8261054/83295544-60e09800-a1ac-11ea-9b93-6a067a2934e5.png)
