### ISSUE TITLE
u/v wind barb adding all colorbars to last subplot

### ISSUE THREAD

**Issue by cgodine** [ARM-DOE/ACT#164]
When plotting multiple subplots using act.plotting.TimeSeriesDisplay.plot_barbs_from_u_v and adding a colormap to the subplots, all of the colorbars end up being plotted on the last subplot rather than their respective subplots:

![](https://dev.arm.gov/~godine/PLOTS/sgp/sgp915rwpwindcon/20200102/sgp915rwpwindconI8.a1.rwp_windcon.20200102.png)

I didn't notice anything in the code that I thought would be causing this. Any ideas?

**Comment by rcjackson** [comment]
Chances are the plt.colorbar command is pointing to the wrong axis in the code. I'd check the ax= keyword in the plt.colorbar command.


________________________________

**Comment by kenkehoe** [comment]
@cgodine did you check if ax= is the issue. If not I'll need to look into it.

**Comment by cgodine** [comment]
@kenkehoe looks like it was indeed pointing to the wrong axis. Made a PR and can close this issue.
