### ISSUE TITLE
ACT Title Missing 'data'

### ISSUE THREAD

**Issue by nhickmon** [ARM-DOE/ACT#172]
The title for the ACT repo is missing 'data' and should read Atmospheric data Community Toolkit

**Comment by AdamTheisen** [comment]
@rcjackson I think you are the only one that can change that in the repo settings.  Assigning to you!

**Comment by rcjackson** [comment]
Went ahead and changed the title.

**Comment by AdamTheisen** [comment]
Thanks Bobby!
