### ISSUE TITLE
Standard in docs and bug in Sphinx

### ISSUE THREAD

**Issue by zssherman** [ARM-DOE/ACT#178]
So I was converting over Py-ARTs docs and ran into something from ACT early on. I remember we had the docs set where parameters had a space on both side of the colon before the parameter type. This is inline with doc styles for major packages. When it stopped working the spaces were removed. It turned out this was an update sphinx did that messed with numpy docs:
https://github.com/readthedocs/sphinx_rtd_theme/issues/766#issuecomment-517145293

The fixed mentioned, however, will fix rtd theme but then centers all tables for parameters which looks ugly, in my opinion.

A way around all these and looks cleaner both standard wise and in the documentation itself is to remove numpy doc and have the sphinx napolean extension and revert to having the space before and after the colon in the docs to keep with standards. I can do a pull request soon if you all wish.

**Comment by AdamTheisen** [comment]
@zssherman thanks for catching that.  I thought it was odd when that issue came up.  If you think that will make the docs look better and @rcjackson doesn't see any issues with it, go right on ahead.

**Comment by AdamTheisen** [comment]
#180 resolved this
