### ISSUE TITLE
Day/night background issues with polar night

### ISSUE THREAD

**Issue by kenkehoe** [ARM-DOE/ACT#181]
The day/night plotting background has issues with astral and calculating times for sun rise/set. This is throwing an error when there is no sun during the day. We can fix that with a try/except.

Other issue is that if a user catches the exception the background for polar night comes out as all day. I think this is an issue with how things are plotted.

<img width="1006" alt="Screen Shot 2020-01-31 at 12 41 59" src="https://user-images.githubusercontent.com/8261054/73569178-20a02180-4427-11ea-9625-f7b10868e4a9.png">

**Comment by AdamTheisen** [comment]
These codes always seem to have issues with high latitude.  Thanks for catching this.

**Comment by AdamTheisen** [comment]
@kenkehoe Where are you getting the lat/lon from, the NAV system?

**Comment by kenkehoe** [comment]
Hmm, looking into the code a bit I think we are not pulling in the NAV data. The lat/lon are coming from the normal data and at MOS that is set to -9999. In ARM files the missing_value indicator is not being set but there are valid_min/valid_max limits. Let me see what I can do and get back to you. We may need to catch this error in data to say don't plot daylight background.

**Comment by AdamTheisen** [comment]
![Figure_1](https://user-images.githubusercontent.com/13421074/74977249-fa4f1f80-53ef-11ea-83ec-e4184ec819d8.png)

I'm having trouble reproducing.  I pulled in nav data and it seems to plot all night fine.

**Comment by AdamTheisen** [comment]
Sounds good @kenkehoe .  I'm debating if we want to through an error or just not plot the background when there's no valid lat/lon.  Thoughts?

**Comment by AdamTheisen** [comment]
Something like this perhaps?

` 
if not (-90 <= lat <= 90) or not (-180 <= lon <= 180): 
    raise ValueError(("Lat or Lon are invalid"))
`

**Comment by kenkehoe** [comment]
Yeah I think something like that to catch the errors of bad values is all we need. Will need to also check if np.isfinite(lat) == True for cases where there is a missing_value attribute and Xarray converts the value to NaN.

I just added the correct values to the Dataset from NAV and it plotted correctly.

![Screen Shot 2020-02-20 at 14 04 44](https://user-images.githubusercontent.com/8261054/74978667-5e6ee500-53ea-11ea-8112-c6dcc2e52256.png)

**Comment by AdamTheisen** [comment]
Added that in along with the finite check to #197
