### ISSUE TITLE
ACT Cheatsheet Needs to be Updated to Reflect ARM-DOE

### ISSUE THREAD

**Issue by AdamTheisen** [ARM-DOE/ACT#192]
Title says it all

**Comment by AdamTheisen** [comment]
Assigning to you, but I can try and figure out how to do update this off the tex.

**Comment by zssherman** [comment]
So the tex is fine just need a new PDF?

**Comment by AdamTheisen** [comment]
@zssherman There were a couple instances in the Tex that still pointed to ANL-DIGR

**Comment by zssherman** [comment]
Gotcha, I did the other locations of the text and changed it to ARM-DOE. The tex II convert using overleaf. You need baposter file too for the format, I can add it to the guides folder,

**Comment by AdamTheisen** [comment]
Resolved with #193
