### ISSUE TITLE
QC Barh Plot for 2D data

### ISSUE THREAD

**Issue by AdamTheisen** [ARM-DOE/ACT#206]
When a user tries to plot 2D-QC data, it currently runs into an error.  It would be good to figure out plots similar to this.

![multi-1d_vars](https://user-images.githubusercontent.com/13421074/76995941-9d775400-691e-11ea-99e1-3afca744225b.png)

**Comment by AdamTheisen** [comment]
@kenkehoe Pulling you in on this to see if you've thought about it.  Plot above is DQ Inspector

**Comment by kenkehoe** [comment]
OK I had not thought about this. I am not surprised it causes an error. Do we want the same plotting response as DQ Inspector?

**Comment by kenkehoe** [comment]
I've got this about 90% complete and just need to get the last bit updated. Should have a PR soon.

**Comment by AdamTheisen** [comment]
@kenkehoe that is great!  Thanks for working on it!

**Comment by kenkehoe** [comment]
I've created a PR for this update. Plot should be as good if not better than DQ Inspector.

![Figure_1](https://user-images.githubusercontent.com/8261054/83085396-07ac2380-a049-11ea-92e9-180d8d28490c.png)

**Comment by kenkehoe** [comment]
This has been resolved. I don't see a way for me to close this issue.

**Comment by AdamTheisen** [comment]
Thanks @kenkehoe !
