### ISSUE TITLE
Shade time series data based on QC

### ISSUE THREAD

**Issue by AdamTheisen** [ARM-DOE/ACT#207]
Some work was started in this area, but I don't think it was finished.  Thhis is to document that we need to finish it.

**Comment by kenkehoe** [comment]
OK. We have this under the keyword assessment_overplot but I think it does need some work.

**Comment by kenkehoe** [comment]
I need to get back to this. The code is currently commented out. I'll try to find some time to get back to this. You can assign this to me.

**Comment by kenkehoe** [comment]
This has been resolved with PR  #244
