### ISSUE TITLE
Create a generic netCDF writer

### ISSUE THREAD

**Issue by kenkehoe** [ARM-DOE/ACT#210]
I think we need to make a generic netCDF writer to handle a few cleanup issues before the data are written to a netCDF file. For example we add some global attributes that we don't want to write to a file. Also, the QC attributes flag_meanings and flag_assessments are string arrays instead of character arrays. CF currently does not allow string attributes. Maybe have some keywords to toggle the actions in case a user wants to keep some but not all of our changes to standardize.

**Comment by AdamTheisen** [comment]
Thanks @kenkehoe
