### ISSUE TITLE
Xarray cannot write ACT object with ARM

### ISSUE THREAD

**Issue by AdamTheisen** [ARM-DOE/ACT#212]
When I try and write the ACT object out to netcdf, I get

TypeError: Invalid value for attr: ARMStandardsFlag.OK must be a number, a string, an ndarray or a list/tuple of numbers/strings for serialization to netCDF files

In the past, I've just dropped this attribute, but we should address the issue.  @rcjackson could we change how this is stored?

**Comment by rcjackson** [comment]
I think we can set OK to 1 and NO_DATASTREAM to 2 instead of auto(). I think that would make it an integer instead of whatever type it’s doing now.

**Comment by rcjackson** [comment]
Or, set this to a bitpacked field

**Comment by AdamTheisen** [comment]
I have to test @kenkehoe new script for writing files, but that could possibly fix this issue.

**Comment by kenkehoe** [comment]
My script will fix this but I think we should still not cause xarray to crash if a user decided to do a quick write to file with .to_netcdf(). I think we should work with xarray as much as we can but not alter it in a way that causes errors. We should convert the ARMStandardsFlag.OK to something that can be written to netCDF file as Bobby suggested. Bit-packed field will work.

**Comment by kenkehoe** [comment]
Is this still an issue? I thought we fixed this?

**Comment by AdamTheisen** [comment]
#243 has resolved this issue
