### ISSUE TITLE
Add method to update object to CF standards

### ISSUE THREAD

**Issue by kenkehoe** [ARM-DOE/ACT#252]
There are are few CF standards that are not part of ARM files or others. Can add suggested attributes to be CF compliant.

**Comment by kenkehoe** [comment]
This can be assigned to me.

**Comment by AdamTheisen** [comment]
@kenkehoe I believe your latest PR satisfies this issue right?  As you mentioned, there are likely some that were missed, but we can update as we find them.  THoughts?

**Comment by kenkehoe** [comment]
Affirm, the last PR covered this issue.
