### ISSUE TITLE
Add method to update units in object

### ISSUE THREAD

**Issue by kenkehoe** [ARM-DOE/ACT#253]
Adding a method to update the variable units in object. Could have option to look for all variable units in same category and make them all the same.

Could also have way to handle incorrect units that cause errors and use a look up table of known fixes.

**Comment by AdamTheisen** [comment]
@kenkehoe Have you seen this at all? https://github.com/xarray-contrib/pint-xarray

**Comment by kenkehoe** [comment]
@AdamTheisen thanks for the link. This looks interesting.

I think we will need to discuss this a bit as there are some promises for this to help, but also some issues.

Issues:
- It appears installing pint-xarray will force us to use xarray=>0.16. We are currently at v0.12 for some other issues. I have not gone back to test again so maybe we can move to v0.16.
- I think there is something still wrong with pint not liking the use of "1" for unitless variables or the symbol of "%". This is a known issue we have code to get around. This does cause issues with code that works on the full dataset so we will need to loop over each variable DataArray to catch the errors and continue even if we are only trying to change on DataArray by calling the method on the dataset.
- I don't like how pint will remove the units attribute when the DataArray values are changed to a pint object, and then add it at the end of the attribute list when it adds it back in. This is not a big deal but it does make an unexpected change.
- In our existing unit conversion function I had to be careful about pint converting data type from int to float and manually convert it back when we don't want that action. I assume that is still part of this and something else we need to be careful to manage.
- Pint will accept a unit of 'degF' but when it writes the units back into the DataArray it writes it as "degree_Fahrenheit" While correct it is not what I asked pint to do. I'd prefer it keeps the unit string I provided of 'degF'.

I think we should write a method to perform the looping on the full dataset by working on each DataArray to ensure the data type and units are set as we expect and catch the ensuing errors. But yeah we should be able to use this new library.

**Comment by kenkehoe** [comment]
I looked into this a bit for a different reason. I would like to still create a method to update units for multiple variables in the object to make matching other data easier. I think that would be straight forward for a method to loop through and update units using existing function we have convert_units(). But I have run into an issue with updating coordinate variables. Using newer Xarray will produce a warning when using *.values to assign new values after unit transformation. It requires using .assign() or .assign_coords() which returns a new object. This could be problematic for a method. I'll look into this pint-xarray to see if it handles coordinate variables correctly. If so we may want to go this route.
