### ISSUE TITLE
Continuous Integration Switch

### ISSUE THREAD

**Issue by AdamTheisen** [ARM-DOE/ACT#255]
Travis-ci.org is switching to travis-ci.com.  Documentation and processes will need to be updated by end of 2020.

**Comment by AdamTheisen** [comment]
Should just be switching the image in the README file for passing or not.

**Comment by AdamTheisen** [comment]
I don't think this was actually implemented as everything .org is still working and nothing on .com works.

**Comment by AdamTheisen** [comment]
It looks like travis-ci.org is read only.  @zssherman @jhemedin we will need to switch over to travis-ci.com now

**Comment by AdamTheisen** [comment]
@rcjackson Pinging you as well since I believe you set up the first CI/tests using the travis-ci.org site.  I need to look more, but do you know offhand if this is an easy fix?

**Comment by zssherman** [comment]
@AdamTheisen I apologize, I didn't see this until now, has this been fixed? I for pyart had to migrate then choose the free plan

**Comment by rcjackson** [comment]
I just fixed it, don’t worry Zach

**Comment by AdamTheisen** [comment]
Now this has been resolved
