### ISSUE TITLE
Replace astral with a different solar calculation library supported on conda-forge

### ISSUE THREAD

**Issue by kenkehoe** [ARM-DOE/ACT#274]
I was recently informed of a different Python library available for use to use for calculating solar positions and times called [pysolar](https://pysolar.readthedocs.io/en/latest/#location-calculation). It is still sub major release but a recent update in Oct. 2020 has me believing it is actively being developed. Initial impressions are that it may be more accurate with solar positions. The sunrise and sunset times are a little different than the Astral times. Comparison to [NREL solar calculator](https://www.esrl.noaa.gov/gmd/grad/solcalc/) are also slightly different. But I don't know how accurate the NREL solar calculator times are.

The documentation is not as good but it does seem to have a few benefits. The accuracy seems to be quite good. Speed for a single calculation is no different than Astral. It is on conda-forge but not the latest version, which is the one we would want. Currently highest version on conda-forge is 0.8. The latest version is 0.9 and available with pip install only.

One benefit is that it is more correct with dates of when the high latitudes transition to/from complete solar night/day. Astral currently does not handle this correctly and misses about 5 days. A second benefit is that it is capable of calculating TOA estimates of solar insolation and surface radiation values from a lat, lon , time entry. Also, able to make estimate of pressure and temperature changes due to elevation change. The additional calculations could be helpful.

If switching to pysolar gave us the ability to pull from conda-forge instead of pipy and more correctly calculates total solar night/day changes I think it is worth the effort to change. Right now I think we need some more digging.

**Comment by AdamTheisen** [comment]
Discussed this on the ACT call today.  Initially, we are going to create a function in ACT that wraps around Astral to provide appropriate solar information.  This will allow greater flexibility for the future if we decide to switch solar libraries.  

In the mean-time, we are going to look at multiple options
- Continue looking at PySolar as an option
- Review skyfield library and if that could be an option
- Review the codes and see if it would make sense to code up the functions in ACT

**Comment by kenkehoe** [comment]
I've started to work on this. There are some nice features to use with skyfield like it's vector processing. But it does not have the ability to produce a noon from a method call. I have it coded up to calculate noon as halfway between sunrise and sunset. This causes issues on full sun days as I can't calculate a noon value. My plan is to finish the refactoring to use a wrapper around the library with an option to use the library for the calculation. I got distracted by some other work so it will be a bit before I can make that PR.

**Comment by brandon-rhodes** [comment]
@kenkehoe — I am not sure which definition of noon you are interested in, but if you are interested in when the Sun transits the local meridian (which is one common definition), you could use Skyfield’s meridian-transit routine by asking it about the Sun:

https://rhodesmill.org/skyfield/almanac.html#meridian-transits

Let me know if there’s a tweak to the documentation that might better draw the eye of folks who need solar noon. Would an example in the Examples chapter, for example, that used this on the Sun have been likely to draw your attention?

**Comment by kenkehoe** [comment]
@brandon-rhodes  thanks for the heads up. Yeah, that works. I think some terminology indicating local solar noon will help those looking for Sun positions who are not astronomers.

**Comment by brandon-rhodes** [comment]
There, I've added this as one of Skyfield's examples, as show in the commit referenced just above. Let me know if you see any typos!

**Comment by AdamTheisen** [comment]
Thanks @brandon-rhodes, that is helpful!  @kenkehoe has informed me that using Skyfield has increased processing time for some of our tests by a factor of 10 which is phenomenal.  Looking forward to seeing what he has worked up to add in to this repo with it.

**Comment by brandon-rhodes** [comment]
> … using Skyfield has increased processing time …

Do you mean that in the sense of “the tests now run faster” or “the tests now run slower”? :slightly_smiling_face:

**Comment by AdamTheisen** [comment]
Ha, that did not come out like I intended @brandon-rhodes .  I meant that it runs 10 times faster.  It's a test that uses an FFT to detect problems with an instrument but depends on knowing when the sun's up to screen out false positives.

**Comment by AdamTheisen** [comment]
Phase one of the work to switch over to Skyfield was merged in after some phenomenal work by Ken.  Going to look at what's remaining that uses astral and fully change over in phase 2

**Comment by AdamTheisen** [comment]
#284 closed this out.  Dependency is officially switched to skyfield.
