### ISSUE TITLE
Errors in Stability Indices Calculation

### ISSUE THREAD

**Issue by AdamTheisen** [ARM-DOE/ACT#296]
Error reported by a user when trying to plot a sonde profile

![image](https://user-images.githubusercontent.com/13421074/110694241-f97d5d00-81ad-11eb-9d97-cb18e33ff9e4.png)

**Comment by AdamTheisen** [comment]
It looks like this was an issue in an older version of MetPy (0.10) and when I installed the newest version, I did not come across the same issue.  We may have to limit the version of MetPy to >=1.0 in the requirements for ACT going forward. @zssherman thoughts?

**Comment by zssherman** [comment]
I would add the requirement, did the user update and solve the issue as well?

**Comment by AdamTheisen** [comment]
@zssherman Yes, the user was going to clone the MetPy repo and install locally.  It's on the ARM systems so there's the system installs that could always but heads with the local install.

**Comment by zssherman** [comment]
Ah gotcha, no way to do a conda environment on that system?

**Comment by AdamTheisen** [comment]
@kenkehoe has figured out a way to build up their own environment on the ARM systems.  I'll let him comment.

**Comment by kenkehoe** [comment]
Yes a conda environment works on ARM servers. They may need to learn how to make conda environments and start them. Maybe point those questions to me.

**Comment by AdamTheisen** [comment]
Closing this out.  Documentation has been updated to denote METPY V1.0 and greater is necessary for those plots.
