### ISSUE TITLE
Run into Issues when reading data from Data Discovery

### ISSUE THREAD

**Issue by ajsockol** [ARM-DOE/ACT#300]
Data downloaded from Data Discovery sometimes includes ".custom" in the netCDF file name.

This can create issues when trying to read the file with ACT.

For example:

    # Import standard libraries
    import act
    import matplotlib.pyplot as plt
    import copy
    import numpy as np
    import math
    from act.utils.data_utils import convert_units

    # Read in PSAP3W1M b1 level netCDF file
    PSAP_object = act.io.armfiles.read_netcdf('sgpaospsap3w1mE13.b1.20210220.000030.custom.nc', decode_times=False)

    # Create a function to help us separate the 1 and 10 um impactor settings, so we can plot AAE from 1 um only
    def impactor_setting_parser(PSAP_object, fields, parse_var, parse_values):
        parse_unit = 'um'
        parse_field = PSAP_object[parse_var].values

        for val in parse_values:
            par_idx = np.where(parse_field == val)[0]

            for field in fields:

                if val == 10.:
                     out_field = PSAP_object[field].values
                else:
                    out_field = np.zeros(len(PSAP_object[field].values))
                    out_field[:] = np.nan

                out_field[par_idx] = PSAP_object[field].values[par_idx]

                PSAP_object[field+'_'+str(int(val))+parse_unit] = (('time'), out_field)

    # Use impactor separator function we just made on the PSAP 1m b1 level netCDF file we just read in (PSAP_object)
    impactor_setting_parser(PSAP_object, ['Ba_B_Weiss', 'Ba_G_Weiss', 'Ba_R_Weiss', 
        'transmittance_blue','transmittance_green','transmittance_red'], 'impactor_state', [1,10])

    figwidth = 10  # width of figure in pixels. 10 = 1000 pixels
    figheight = 3  # width of figure in pixels. 3 = 300 pixels
    n_plots = 2
    lm, bm, rm, tm, ws, hs = 0.10, 0.08, 0.75, 0.95, 0.275, 0.275
    subplot_shape = (n_plots, )

    display = act.plotting.TimeSeriesDisplay(PSAP_object, subplot_shape=subplot_shape, figsize=(figwidth, 
        subplot_shape[0]*figheight))
    display.fig.tight_layout()
    display.fig.subplots_adjust(left=lm,right=rm, bottom=bm, top=tm, wspace=ws, hspace=hs)

    plot_fields = ['Ba_B_Weiss_10um','Ba_B_Weiss_1um','Ba_G_Weiss_10um','Ba_G_Weiss_1um',
        'Ba_R_Weiss_10um','Ba_R_Weiss_1um','impactor_state']

    plot_colors = ['blue', 'lightblue', 'green', 'lightgreen','red', '#ff8c69','C0']
    plot_labels = ['Blue λ, 10μm', 'Blue λ, 1μm','Green λ, 10μm', 'Green λ, 1μm','Red λ, 10μm', 'Red λ, 1μm','Impactor State']

    plot_titles = ['Absorption Coefficients','Impactor Setting']

    pn  = [0,0,0,0,0,0,1]
    axs = [0,0,0,0,0,0,0]

    for i, field in enumerate(plot_fields):

        display.plot(field, subplot_index=(pn[i], ), label=plot_labels[i], linestyle='', day_night_background=True, markersize=4, 
            color=plot_colors[i])
        display.axes[pn[i]].legend(loc='upper left', frameon=False,  bbox_to_anchor=(1.05, 1.04))   
        display.axes[pn[i]].set_title('SGP PSAP' + ' ' + plot_titles[pn[i]])
        display.axes[pn[i]].set_ylabel('1/Mm')

    # Calculate AAE from b1 level PSAP data
    Blue_coefficient = PSAP_object['Ba_B_Weiss_1um']
    Red_coefficient = PSAP_object['Ba_R_Weiss_1um']
    Green_coefficient = PSAP_object['Ba_G_Weiss_1um']
    Blue_wavelength = 464.0
    Red_wavelength = 648.0
    Green_wavelength = 529.0
    AAE_BlueGreen = (np.log(Blue_coefficient/Green_coefficient))/(np.log(Green_wavelength/Blue_wavelength))
    AAE_BlueRed = (np.log(Blue_coefficient/Red_coefficient))/(np.log(Red_wavelength/Blue_wavelength))
    AAE_GreenRed = (np.log(Green_coefficient/Red_coefficient))/(np.log(Red_wavelength/Green_wavelength))
    # c1_AAE = PSAP_c1_object['AAE_BG_1um'].values

    #Add these new calculated values to the netCDF file as new variables
    PSAP_object = PSAP_object.assign(AAE_BlueGreen=AAE_BlueGreen)
    PSAP_object = PSAP_object.assign(AAE_BlueRed=AAE_BlueRed)
    PSAP_object = PSAP_object.assign(AAE_GreenRed=AAE_GreenRed)

    #Plot Calculated AAE Values
    figwidth = 10  # width of figure in pixels. 10 = 1000 pixels
    figheight = 3  # width of figure in pixels. 3 = 300 pixels
    n_plots = 1
    lm, bm, rm, tm, ws, hs = 0.10, 0.2, 0.75, 0.9, 0.275, 0.275
    subplot_shape = (n_plots, )

    display = act.plotting.TimeSeriesDisplay(PSAP_object, subplot_shape=subplot_shape,
        figsize=(figwidth, subplot_shape[0]*figheight))
    display.fig.tight_layout()
    display.fig.subplots_adjust(left=lm,right=rm, bottom=bm, top=tm, wspace=ws, hspace=hs)

    plot_fields = ['AAE_BlueGreen','AAE_BlueRed','AAE_GreenRed']

    plot_colors = ['blue','green','red']
    plot_labels = ['BlueGreen, 1μm','BlueRed, 1μm','GreenRed, 1μm']

    plot_titles = ['AAE_BG_1um','AAE_BR_1um','AAE_GR_1um']

    pn  = [0,0,0]
    axs = [0,0,0]

    for i, field in enumerate(plot_fields):

        display.plot(field, subplot_index=(pn[i], ), label=plot_labels[i], linestyle='', day_night_background=True, markersize=4, 
            color=plot_colors[i])
        display.axes[pn[i]].legend(loc='upper left', frameon=False,  bbox_to_anchor=(1.05, 1.04))   
        display.axes[pn[i]].set_title('SGP PSAP calculated' + ' ' + plot_titles[pn[i]])
        display.axes[pn[i]].set_ylabel('unitless')

    plt.show()

    PSAP_object.close()

Running this code returns the following error:

![image](https://user-images.githubusercontent.com/49569746/111657739-b9376380-87d9-11eb-8987-a7a038ac84b3.png)

But the error goes away when the ".custom" is removed.

**Comment by AdamTheisen** [comment]
Thanks @ajsockol !  I'll have to take a look as we might be getting date/time information from the filename which is not going to be robust.

**Comment by kenkehoe** [comment]
I think the date is being parsed from end of filename so when the file is modified and the .custom. part is added the numbers don't work. I think we can fix this by counting from the start of the filename. But as @AdamTheisen  suggested getting the date/time from filename is not best. Maybe we can use time in the file.

**Comment by kenkehoe** [comment]
Sounds good.

**Comment by kenkehoe** [comment]
I think this is complete, correct?

**Comment by AdamTheisen** [comment]
Completed
