### ISSUE TITLE
Functions not showing up in documentation

### ISSUE THREAD

**Issue by AdamTheisen** [ARM-DOE/ACT#321]
I was trying to search and/or view the page for our datafilter function but it's not showing up in the ACT documentation.  I can see it on this list but can't click on it like others.

https://arm-doe.github.io/ACT/API/generated/act.qc.qcfilter.QCFilter.html

**Comment by zssherman** [comment]
I'll take a look, could just be a mistyped docstring

**Comment by zssherman** [comment]
Found the issue doing a PR now @AdamTheisen

**Comment by AdamTheisen** [comment]
Done with lastest pr
