### ISSUE TITLE
ARM DQR to QC adding multiple qc tests for same DQR

### ISSUE THREAD

**Issue by AdamTheisen** [ARM-DOE/ACT#323]
When i tried plotting up multiple days of a dataset with DQR periods spread across those days each periods was added as a separate QC flag in the qc variable.  I.e. there were 5 tests with the same name with different corresponding times.  We need to look at a more robust way to add these DQRs to the qc variables

**Comment by AdamTheisen** [comment]
![dqr_issue](https://user-images.githubusercontent.com/13421074/117345869-abfb3480-ae6c-11eb-8826-600e7c74a86c.png)

Plot showing issue

**Comment by kenkehoe** [comment]
Ummm, that is strange. I'll take a look.

**Comment by kenkehoe** [comment]
I believe this has been resolved.
