### ISSUE TITLE
DeprecationWarnings

### ISSUE THREAD

**Issue by kenkehoe** [ARM-DOE/ACT#342]
There are a few warnings I need to track for updates so I'm going to lump them all under here until they are fixed. You can assign this issue to me.

- act/qc/qcfilter.py:737: DeprecationWarning:`np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here. Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

**Comment by AdamTheisen** [comment]
Thanks @kenkehoe !  I thought I had gotten these all, but I guess not!

**Comment by kenkehoe** [comment]
Resolved under PR #343
