### ISSUE TITLE
day_night_background throws error when no location info in file

### ISSUE THREAD

**Issue by rcjackson** [ARM-DOE/ACT#37]
We need to check if there is location data in the file before calling day_night_background. Right now it crashes if plotting the background with no location data, but we can just make it not do the background if there is no location information.

**Comment by kenkehoe** [comment]
Additional feature request for this. 
- Handle vectors if it currently can't. (1D a 2D?)
- Handle vectors with the first value set to NaN. Need to look for first finite value and use.
- Handle a value for lat but not lon and exit gracefully.

**Comment by kenkehoe** [comment]
I believe I put in a try to solve the initial issue for this Issue. I think it will handle scalar and 1D location data. Don't know about the rest of the bullets.

**Comment by kenkehoe** [comment]
I will take a look at finishing this. You can assign it to me.

**Comment by AdamTheisen** [comment]
Resolved with #211
