### ISSUE TITLE
Tests for Python3.7 not completing

### ISSUE THREAD

**Issue by AdamTheisen** [ARM-DOE/ACT#385]
@zssherman there's something strange going on with the travis build for Python 3.7 after PR #383. The build looks to be stalling on the test_io module.  Python3.8 passed though.  Is there anything in the recent PR that may have caused this that you can think of?

**Comment by zssherman** [comment]
None of the changes, shouldn't have effected it. I reran the CI PR and it seems to run fine.

**Comment by zssherman** [comment]
and that PR is after that other PR, so couldn't have been a random timeout connection issue.

**Comment by AdamTheisen** [comment]
@zssherman you just reminded me that the ADC was doing some database updates this morning which may have caused some timeout issues.  Will close this out.
