### ISSUE TITLE
Adding qc tests becomes very slow for datasets with a large number of variables

### ISSUE THREAD

**Issue by maxwellevin** [ARM-DOE/ACT#391]
I'm supporting a `tsdat` data user who has with a dataset with 300+ variables in that they want to apply some qc to. Tsdat uses the `act` `qcfilter.add_test(...)` dataset accessor under the hood to record the results of our quality checks and we're finding that for large datasets this method can quickly get prohibitively expensive. At first I thought it was because we had to generate and attach new `DataArray` objects to the dataset for each quality check, but I noticed no speedup at all for `ds.qcfilter.add_test(...)` when I created the qc variables in advance.

Here's a basic example I created to illustrate what I'm seeing:

```python
def run_example(n_variables, n_samples=100):
    time = pd.date_range(
        start="2022-02-17 00:00:00",
        end="2022-02-18 00:00:00",
        periods=n_samples + 1,
    )

    # Create data variables and initialize QC variables to 0
    noisy_data_mapping = {f"data_var_{i}": np.random.random(time.shape) for i in range(n_variables)}
    qc_vars = {f"qc_data_var_{i}": np.zeros(time.shape) for i in range(n_variables)}
    qc_vars.update(noisy_data_mapping)

    ds = xr.Dataset(
        data_vars={name: ("time", data) for name, data in noisy_data_mapping.items()},
        coords={"time": time},
    )


    start = datetime.datetime.now()
    for name, var in noisy_data_mapping.items():
        failed_qc = var > 0.75  # Consider data above 0.75 as bad. Negligible time here.
        ds.qcfilter.add_test(
            name,
            index=failed_qc,
            test_number=1,
            test_meaning="Value above threshold.",
            test_assessment="Bad",
        )
    end = datetime.datetime.now()
    print(f"Time elapsed = {(end-start)}")
```

When I run this code on my laptop for various values of `n_variables` I got the following results:
```
n_variables = 25 --> 0.5 seconds
n_variables = 50 --> 3.8 seconds
n_variables = 100 --> 35 seconds
n_variables = 200 --> 643 seconds
```

Roughly speaking, doubling the number of variables in the dataset seems to result in a tenfold increase in the time taken to add qc tests to that dataset, though the jump from `n_varables = 100` to `n_variables = 200` is more like a 20x increase. Oof.

**Comment by maxwellevin** [comment]
Using a profiler sheds even more light on what's going on. Here's the results of the profiler for `n_variables = 100`:

<img width="1297" alt="image" src="https://user-images.githubusercontent.com/24307537/154628894-631cf18a-e472-4012-9bb2-e78971256520.png">


From this it is clear that the `matched_qc_variables` property in `act.qc.clean.py` is where all of the time is spent in the example code I posted. Here's the offending method:
https://github.com/ARM-DOE/ACT/blob/462ac5e4a6895a63da702ce57250716646898659/act/qc/clean.py#L23-L76

In particular, the triply-nested for-loop is the main resource hog. If I comment out that block entirely, then the same code with `n_variables = 100` takes only 4 seconds to run.

Can this method be optimized? Maybe there are some tricks we can use; i.e. if `check_arm_syntax` is `True` and the dataset has variables that start with `qc_` then can we skip the nested for-loop? If not, are we able to cache any part of this so that future property accesses are less expensive?

**Comment by AdamTheisen** [comment]
Thanks for reporting this @maxwellevin!  One of our priorities with our second roadmap is optimization so this is perfect timing.  We'll take a look and see what we can do to improve this!

**Comment by maxwellevin** [comment]
@AdamTheisen Awesome, thanks for taking a look at it! 

Is your roadmap publicly-available? Just curious about what you all have planned & the timelines for all that.

**Comment by AdamTheisen** [comment]
@maxwellevin it's on my list to merge in today!

**Comment by AdamTheisen** [comment]
@kenkehoe Just wanted to get your thoughts here.

There are a number of for loops in this and we can get rid of one at least.  Since att_name is scalar and there shouldn't be multiple dictionary keys with att_name we can get rid of the last for right?  I like @maxwellevin suggestion but I still think there's a way to optimize this more...

```
         for var in self._obj.data_vars: 
             attributes = self._obj[var].attrs 
             for att_name in attributes: 
                 if att_name in qc_dict.keys(): 
                     for value in qc_dict[att_name]: 
                         if re.match(value, attributes[att_name]) is not None: 
                             variables.append(var) 
                             break 
```

**Comment by kenkehoe** [comment]
Interesting @AdamTheisen  I'll take a look.

**Comment by AdamTheisen** [comment]
A new release is out there with this fix so will be closing.  Thanks @maxwellevin and @kenkehoe !
