### ISSUE TITLE
Add additional files to exclude from codecov

### ISSUE THREAD

**Issue by mgrover1** [ARM-DOE/ACT#397]
After submitting #396 , I noticed that codecov percentage decreased... we should _probably_ add the `docs` directory to the `omit` list [here](https://github.com/ARM-DOE/ACT/blob/master/.coveragerc)

**Comment by AdamTheisen** [comment]
Thanks @mgrover1 ! We normally have a decrease of 0.5 to 0.6% that I believe is due to some unit tests on APIs that only run on merge. I'll check some more tomorrow and provide a detailed list.

**Comment by mgrover1** [comment]
Okay! Good to know!

**Comment by mgrover1** [comment]
@AdamTheisen should I go ahead and close this then? Since the issue raised wasn't what's going wrong?

**Comment by AdamTheisen** [comment]
Yes, I think we can close this
