### ISSUE TITLE
Add Docs on Setting Environment Variables or Dealing with Keys/Passwords

### ISSUE THREAD

**Issue by mgrover1** [ARM-DOE/ACT#399]
While working on #380 , I realized that the documentation does not mention that the user needs to set environment variables such as `ARM_USERNAME`, `ARM_PASSWORD`, or the new `AIRNOW_TOKEN` variable, which contain sensitive information required to access the data apis...

The user needs to set these before they can run through their testing locally... what are your thoughts here @AdamTheisen ?

We could think about finding a different approach here by having some sort of configuration file? Not sure what the best approach would be...

**Comment by AdamTheisen** [comment]
@mgrover1 That's a good question.  Essentially, we've been under the assumption that the users won't really run the unit tests locally so we didn't put much though into making it more easily accessible and even then, if they run locally, the tests should skip the ones that use those environment variables in the event they don't have them set.  Thoughts?

**Comment by AdamTheisen** [comment]
See #477 .  Process is to add secrets to Github, add those secrets to the environment in the github actions config files, and then get those environment variables in the script the normal way such as os.getenv.
