### ISSUE TITLE
Groupby Plots

### ISSUE THREAD

**Issue by AdamTheisen** [ARM-DOE/ACT#402]
It would be beneficial to add a function that will plot data grouped by certain periods of time.  For instance, the following is fake data that's grouped and plotted by year.  Goal would be to provide generic function to handle groupby's for day, month, year.  

Year Grouping
![image](https://user-images.githubusercontent.com/13421074/156261678-622b47c7-987d-4b6e-8ddb-e27b297ba638.png)

Month Grouping
![image](https://user-images.githubusercontent.com/13421074/156262963-15ff4250-a576-42d3-bf11-9d1a3fd134b7.png)

**Comment by zssherman** [comment]
@rcjackson Has there been any progress on this? See you self-assigned

**Comment by rcjackson** [comment]
@zssherman It fell of my priority list given the craziness of last summer, but I just put it back on and will start to look at it at the end of this week

From: Zach Sherman ***@***.***>
Date: Wednesday, February 15, 2023 at 9:33 AM
To: ARM-DOE/ACT ***@***.***>
Cc: Jackson, Robert ***@***.***>, Mention ***@***.***>
Subject: Re: [ARM-DOE/ACT] Groupby Plots (Issue #402)

@rcjackson<https://github.com/rcjackson> Has there been any progress on this? See you self-assigned

**Comment by zssherman** [comment]
@rcjackson Cool! Let me know if there is anything I can do to help with this

**Comment by AdamTheisen** [comment]
Closing out since @rcjackson did some great work on this in PR #621
