### ISSUE TITLE
Update cftime to datetime64 values

### ISSUE THREAD

**Issue by kenkehoe** [ARM-DOE/ACT#430]
We had issues with reading time not formatted to the way Panda's expected and had to update to use cftime. My implementation of the cftime to datetime64 is not as slick as using 

ds['time'] = ds.indexes['time'].to_datetimeindex()

Should look into this better fix.

**Comment by mgrover1** [comment]
@kenkehoe are you suggesting rewriting the current implementation using that one-liner?

**Comment by kenkehoe** [comment]
@mgrover1  I'm not sure what I mean now. I looked into it and this different implementation seemed better but did cause another issue. I need to look into this some more.

**Comment by kenkehoe** [comment]
I'm going to close this. The currently works and I don't see the benefit of changing.
