### ISSUE TITLE
Keep variables option for reading

### ISSUE THREAD

**Issue by kenkehoe** [ARM-DOE/ACT#431]
Currently we can only make reading faster or Dataset smaller by using drop_variables keyword. But this requires proper knowledge of the variables we do not want to read. Would be better if we can have a keep_variables keyword.

Apparently we can use xarray reading methods with chunks set to empty dictionary to have xarray only read metadata, not data. This could then allow us to implement a keep_variables keyword.

Other option the DQ Office implemented was to read the data file with netcdf4 first to get metadata, then use that to determine the variable names to exclude.

**Comment by AdamTheisen** [comment]
Thanks @kenkehoe this does sound like it would be useful. @mgrover1 something you would want to take on?

**Comment by kenkehoe** [comment]
I have a little time to look into this now. This is something the DQ Office uses every day and would be nice to move from our dqlib repo to ACT.

You can assign this issue to me.
