### ISSUE TITLE
ARM Webservice Only works with Dates with -

### ISSUE THREAD

**Issue by AdamTheisen** [ARM-DOE/ACT#448]
We should add some more robust processing to the get_armlive download_data module.  When passing in an ARM formatted date (20220101) it does not work and expects 2022-01-01.  We should add some catches for that and additional catches for "not real" dates like 2022-04-31 so that we use the nearest date.

**Comment by zssherman** [comment]
I'll take a shot at this.

**Comment by mgrover1** [comment]
@AdamTheisen what if we took in a date time instead of a string?

**Comment by kenkehoe** [comment]
I think taking in a datetime as one of the options is a good idea, but would prefer we not limit it to just a datetime. I think using dateparser if string, use datetime.datetime or numpy.datetime64 if that is used.

**Comment by AdamTheisen** [comment]
#449  has resolved the initially reported issue
