### ISSUE TITLE
qc_flag_block_plot Errors: KeyError for flag_masks, ValueError for ancillary variable, etc.

### ISSUE THREAD

**Issue by gg2** [ARM-DOE/ACT#454]
I encounter various errors attempting to load QC plots.
I'm using ACT to generate plots programmatically from any arbitrary ARM dataset. I use act.plotting.TimeSeriesDisplay to get an initial object/plot -- call it ts_display.
I then look for companion QC data.
If that appears to exist, I call ts_display.qc_flag_block_plot(data_var_name, subplot_index=(1,))
So, I already know the data var and its qc var exist. I'm checking for that before making ACT calls.

For one example, the QC variable does not have a flag_masks attribute. It has flag_method = bit and other regular ARM QC attributes, but did not have that added. ACT fails with "<class 'KeyError'>: 'flag_masks'"
For another example, ACT fails with "<class 'ValueError'>: No quality control ancillary variable in Dataset for {data_var_name}". But the data var definitely has an attribute ancillary_variables that references qc_<data_var_name> (along with other associated variables). And qc_<data_var_name> definitely exists in the dataset as well.

Are there some improvements to make qc_flag_block_plot more robust? Is there anything I might do to handle it better, so it is more likely to successfully load the QC variable plot?

Also, as a tag-along that I'll mention briefly here, I'm trying to dynamically resize the plot based on whether QC data exists or not. I need to look up which MatPlotLib methods I was using to do that. While I experimented with them successfully outside of ACT to resize plots, and even see ACT uses them itself to dynamically determine subplots, when I used them, the results are unsatisfactory. If I remember right, the 1st plot gets cut off after resizing (if QC ended up failing to load), or resizing doesn't work at all, etc. 
I'll revisit what I did and come back with a 2nd issue post for that specifically.
But, in terms of the QC data loading or not, the thought for here might be that it would be fantastic to have a better automated way to resize the plot depending whether QC data did exist, or successfully loaded, and to not display a big empty white-space if it didn't. But, I also realize that might require too much guesswork about which subplot that entails, etc. So, just a thought, in case it could happen.

**Comment by gg2** [comment]
An example for the KeyError, on ADC servers:
/data/home/sivaraman/data/datastream/sgp/sgprnccnprof1kulkarniC1.c1 -- ccn_1 and qc_ccn_1 variables.
An example for the ValueError:
/data/home/gibler/vap/aodbe/DATA/data/datastream/sgp/sgpaodbe2chC1.c1 -- aod_be_870 and qc_aod_be_870 variables.

**Comment by kenkehoe** [comment]
@gg2  I'll take a look. Are you running the dataset_name.clean.cleanup() method on the Dataset before plotting. ARM's QC does not work directly with the internal logic. The ARM QC needs to be converted to CF QC before the QC will work.

**Comment by kenkehoe** [comment]
This is working for me.

```
import act
import matplotlib.pyplot as plt

filename = '/data/home/sivaraman/data/datastream/sgp/sgprnccnprof1kulkarniC1.c1/sgprnccnprof1kulkarniC1.c1.20160929.000500.nc'

ds_object = act.io.armfiles.read_netcdf(filename)
ds_object.clean.cleanup()

my_disp = act.plotting.TimeSeriesDisplay({'sgprnccnprof1kulkarniC1.c1': ds_object}, subplot_shape=(2,), figsize=(15, 10))
my_disp.plot('ccn_1', subplot_index=(0,))

my_disp.qc_flag_block_plot('ccn_1', subplot_index=(1,))
plt.show()
```

**Comment by gg2** [comment]
OK. No, I haven't known about that. I was working from the example on this page, which mentions querying ARM data and uses qc_flag_block_plot, but not the cleanup you mentioned:
https://arm-doe.github.io/ACT/source/auto_examples/plot_qc.html#sphx-glr-source-auto-examples-plot-qc-py

Looks like it might be good to expand that example. Is it not necessary there for some reason?

I'll give the cleanup method a try, and let you know how it goes.

**Comment by AdamTheisen** [comment]
@gg2 thanks for catching that!  We automatically apply the cleanup in that add_dqr_to_qc function so that we can work with the QC.  I am putting together an ACT tutorial for the open-science workshop that does showcase this if interested: https://github.com/AdamTheisen/ARM-Notebooks/blob/main/Open-Science-Workshop-2022/tutorials/act-basics.ipynb

It would be good to add an example like this to the ACT documentation though.  I'll see what I can do!

**Comment by gg2** [comment]
cleanup did fix the issue. I get QC plots now. I'll give the notebook a look.

The basics of what I'm doing are exactly that page I referenced. But it's reordered and a little more convoluted (and includes error-checking and all) because I'm trying to control the plot output based on whether there is QC or not, and whether it successfully loads or not.

**Comment by gg2** [comment]
@AdamTheisen For looking at the qc.arm.add_dqr_to_qc code and the notebook now, I think it is good to point out the clean method separately. From my perspective, for what I'm trying to accomplish, I'm not sure I would need or want the add_dqr_to_qc part. ACT is promoted as what I should move to for examining ARM data. But I think I'm mainly trying to examine what is actually in the netCDF files, vs attempting to get the best quality weather data. So, maybe development/data processing concerns vs scientific/user concerns? So, for not having a broad enough knowledge of all the pieces in play, that's where I arrive at thinking it's good to always point out cleanup separately from add_dqr -- as you've done in the notebook presentation.

**Comment by kenkehoe** [comment]
@gg2 good points. @AdamTheisen let's add a call to .clean.cleanup() in the example to be explicit about cleaning up the Dataset.

I'll see about putting together an example with the way I would go about checking if a QC variable exits to indicate the number of plots to plot.

**Comment by kenkehoe** [comment]
@AdamTheisen  do you think we should a keyword in act.io.armfiles.read_netcdf() to apply .clean.cleanup()? That would be one less extra call after reading and may be a way to get documentation into the read_netcdf() function on the need to apply QC cleanup.

**Comment by AdamTheisen** [comment]
@kenkehoe I like that idea. We would want the default to be False though right? Or we could default to True since it is an ARM netcdf reader. Open to options though

**Comment by kenkehoe** [comment]
@gg2 here is an updated version with how I would handle the second plot that is dependent on existence of QC variable.

```
import matplotlib.pyplot as plt
from act.plotting import TimeSeriesDisplay
from act.io.armfiles import read_netcdf

filename = '/data/home/sivaraman/data/datastream/sgp/sgprnccnprof1kulkarniC1.c1/sgprnccnprof1kulkarniC1.c1.20160929.000500.nc'

ds_object = read_netcdf(filename)
ds_object.clean.cleanup()

var_name = 'ccn_1'
num_plots = 1
if ds_object.qcfilter.check_for_ancillary_qc(var_name, add_if_missing=False):
    num_plots = 2

my_disp = TimeSeriesDisplay(
    {'sgprnccnprof1kulkarniC1.c1': ds_object},
    subplot_shape=(num_plots, ),
    figsize=(15, 5 * num_plots))

my_disp.plot(var_name, subplot_index=(0, ))

if num_plots > 1:
    my_disp.qc_flag_block_plot(var_name, subplot_index=(1, ))

plt.show()
```

**Comment by kenkehoe** [comment]
@AdamTheisen I think setting the cleanup to False as default is best. I see the reader as more generic than just ARM netCDF files.

**Comment by gg2** [comment]
Nice. @kenkehoe that's essentially what I did. Yours is a little simpler to read and apply. The main difference I added in was a check for errors and attempt to resize the plot if qc_flag_block_plot failed (which it was doing, since I wasn't using cleanup). Also, your usage of qcfilter is good. I should switch to that. This is what I have (snipped from a bigger context):

```
    try:
        nc_data = act.io.armfiles.read_netcdf(files_list)
        nc_data.clean.cleanup()

        if var_name not in nc_data:
            raise KeyError("Variable not in dataset.")
        has_qc = True if 'qc_'+var_name in nc_data else False

        ts_display = act.plotting.TimeSeriesDisplay(
            nc_data,
            figsize=(19,11 if has_qc else 5.5),
            subplot_shape=(2 if has_qc else 1,),
        )
    except Exception as e:
        result['errors'].append("Error fetching or plotting netCDF data, {}:\n{}".format(type(e), e))
    else:
        if has_qc:
            try:
                ts_display.qc_flag_block_plot(var_name, subplot_index=(1,))
            except Exception as e:
                result['errors'].append("QC error, {}: {}".format(type(e), e))
                ts_display.fig.delaxes(ts_display.axes[1])
                #ts_display.fig.set_size_inches(19,5.5)
                #ts_display.axes[0].change_geometry(1,1,1) # Try rearranging this and the previous line?
        ts_display.plot(var_name, subplot_index=(0,))
        ts_display.fig.tight_layout()

        fig_bytes = io.BytesIO()
        plt.savefig(fig_bytes)
        result['img'] = base64.b64encode(fig_bytes.getvalue()).decode()
```

Also note, the comments are what I mentioned about attempting to resize the plot again, if QC failed. That's where I left off with it. subplot(1) gets cut off, where normally, if only 1 subplot in the first place, it fits fine. Doing all the resizing causes something to shift or not be interpreted the same.

**Comment by kenkehoe** [comment]
@gg2  if you are trying to adjust the margins around the plots I've found 

`ts_display.fig.subplots_adjust(left=0.1,right=0.85, bottom=0.08, top=0.95, hspace=0.2)`

works better. Also, using the ds_object.qcfilter.check_for_ancillary_qc() may be better as the datastreams are not always consistent and we try to make things right in the Dataset but there are some non-standard stuff in an "ARM standard" datastream. It's possible for a QC variable to not be "qc_" + var_name.

**Comment by kenkehoe** [comment]
Offline discussion with Gabe indicate this issue has been resolved. I will add a keyword to read_netcdf() to apply .clean.cleanup().
