### ISSUE TITLE
Need a new plot module to allow for non-time plotting on X-axis

### ISSUE THREAD

**Issue by AdamTheisen** [ARM-DOE/ACT#459]
There's been a request to allow for non-time plotting on the xaxis, like solar zenith or other variables.  A new plotting module for x-y plots and not specifically time series would be beneficial.

**Comment by AdamTheisen** [comment]
@cgodine did you ever get something going for this one?  If not, I can always take a first pass at it.

**Comment by zssherman** [comment]
I think this was tackled in #683 can probably close.

**Comment by AdamTheisen** [comment]
@zssherman I missed your comment but agree!  This was covered in scatter plot feature.
