### ISSUE TITLE
Exclude Test Data from Packaging

### ISSUE THREAD

**Issue by mgrover1** [ARM-DOE/ACT#470]
As was raised in #468 , it would be good to exclude the data files from packaging, which would cut down the space by ~68 mb. If users are interested in using it, they can clone the repo, and access it from there.

**Comment by zssherman** [comment]
If we have the location, I can always change the code over.

**Comment by mgrover1** [comment]
We can move ahead with this!

**Comment by zssherman** [comment]
@mgrover1 Where is the data going to be stored? Trying to think of how or where to pull it from

**Comment by kenkehoe** [comment]
ARM is going through some FTP security changes. I wonder if we had a second GitHub repo of just data files we could avoid any future problems? Also, would be self contained all in GitHub vs. spread across different entities.

**Comment by zssherman** [comment]
@mgrover1 Makes made good progress on getting the repo up for the data. I added the rest of the test files in a PR to the repo, once that's done and v2 goes through so there isn't conflicts and overlap, I can change the testing calls to use the arm_data repo for the testing.

**Comment by mgrover1** [comment]
@zssherman - I cut the first release(s) of `arm-test-data`, and it is installable via pypi! Waiting on feedback on the conda-forge recipe, but that should be good to go by tomrrow.

**Comment by zssherman** [comment]
@mgrover1 Awesome sounds good!
