### ISSUE TITLE
Plotting flag variables

### ISSUE THREAD

**Issue by AdamTheisen** [ARM-DOE/ACT#472]
### Discussed in https://github.com/ARM-DOE/ACT/discussions/471

<div type='discussions-op-text'>

<sup>Originally posted by **maxwellevin** June  3, 2022</sup>
Hi act-atmos team, 

I'm working with some ARM data that has a state indicator variable I want to plot. In my case I am working with there is a `cloud_phase` variable which looks something like this:

```
cloud_phase(time, height):byte*
    long_name = Thermodynamic Cloud Phase
    units = 1
    flag_values:byte = 0, 1, 2, 3, 4, 5, 6, 7, 8
    flag_meanings = clear_sky liquid ice mixed_phase drizzle liquid_drizzle rain snow unknown
    missing_value:byte = -1
    _FillValue:byte = -1
```

So a value of 0 indicates clear sky, 1 indicates liquid, 2 indicates ice, etc. Note this is a bit different than QC variables because the value of `cloud_phase` will always match one of the `flag_values` or `_FillValue` exactly, whereas qc variables can match multiple `flag_masks` / bits to indicate a combination of different states. In other words the different states of the `cloud_phase` variable are mutually exclusive.

I want the plot to look something like this:
<img width="1199" alt="image" src="https://user-images.githubusercontent.com/24307537/171961868-688bcb04-7c3b-4efb-9ac3-60fda851152c.png">

To the best of my knowledge, `act` doesn't quite do this yet (though it does do superbly with plotting qc variables). It would certainly be beneficial to me if the `act.plotting` module could be expanded to provide a method to plot mutually exclusive state indicator variables, so I wanted to float the idea to you all and see if you think it's worthwhile.

## Reference

ARM Standards §6.5 discusses how ARM handles exclusive and inclusive state indicator variables:
https://www.arm.gov/publications/programdocs/doe-sc-arm-15-004.pdf

The CF Conventions also discuss variable flags here:
https://cfconventions.org/cf-conventions/cf-conventions.html#flags

</div>

**Comment by AdamTheisen** [comment]
I think we could do this through the existing plot function in TimeSeries but by passing in some discrete shading keywords and information.

**Comment by kenkehoe** [comment]
I think you are correct @AdamTheisen. Should we look into making this a plotting option that correctly handles the flag_values, flag_meanings? Is that something that would be used often enough?

**Comment by AdamTheisen** [comment]
@kenkehoe I was thinking more of a generic discrete colorbar style plotting with the ability to pass in a dictionary of values/meanings.  I think that would be used more than basing it off the flag_values/flag_meanings keywords

**Comment by kenkehoe** [comment]
@AdamTheisen  good point. I'll look into this. You can assign this to me. I think we can show some simple code to transform flag_values and flag_meanings into the dictionary to pass in, as you suggest. That will handle all cases.

**Comment by mgrover1** [comment]
Can we close this @AdamTheisen ?

**Comment by AdamTheisen** [comment]
Yes @mgrover1 !  @maxwellevin please check out @kenkehoe recent additions and the example and let us know if that works for your purposes.  Thanks!

https://arm-doe.github.io/ACT/source/auto_examples/plot_state_variable.html#sphx-glr-source-auto-examples-plot-state-variable-py

**Comment by maxwellevin** [comment]
This looks good to me, nice work @kenkehoe! I'll be using this feature for some new ARM vaps coming soon 😄
