### ISSUE TITLE
Continue readers for NOAA PSL Data

### ISSUE THREAD

**Issue by AdamTheisen** [ARM-DOE/ACT#487]
There's a lot of different instruments deployed in the NOAA PSL Netowrk, developing readers for these would be beneficial, including with the upcoming AMF3 campaign coming up that will be in the vicinity of Courtland Airport

https://psl.noaa.gov/data/obs/sites/view_site_details.php?siteID=ctd

**Comment by AdamTheisen** [comment]
Checklist of readers that need to be developed
- [ ] 915 MHz Wind Profiler Wind
- [ ] 915 MHz Wind Profiler Temperature
- [ ] 449 MHz Wind Profiler Wind
- [ ] 449 MHz Wind Profiler Temperature
- [ ] 3 GHz S-Band Moments
- [ ] Disdrometer Parsivel Optical
- [ ] Surface Meteorology (Data Logger CR100 link) - This has most of the other variables so would reduce readers
- [ ] GPSTrimble NetRS (Water Vapor)

**Comment by mgrover1** [comment]
With #490 merged, we now have two readers in! Planning on taking a look at the other frequency wind profilers after SciPy to make sure the current readers support those...

**Comment by kenkehoe** [comment]
I've been looking at SurfaceMet for NOAA PSL data as part of SAIL. I have an idea for the generic reader. Turns out the downloader pulls from the RAW area which does not have file headers in the file or documentation on the data. I'm looking into understanding this now and have an idea on how to resolve the different files.

**Comment by AdamTheisen** [comment]
The FMCW read might work for the S-band moments as well.  Will have to test a little though

**Comment by kenkehoe** [comment]
@AdamTheisen I think my recent PR resolves Surface Meteorology (Data Logger CR100 link). Shall we check that one off the list?

**Comment by AdamTheisen** [comment]
Done!

**Comment by AdamTheisen** [comment]
I'm removing the GPS one from the list for now.  The documentation does not line up with the readable file so there is no way of telling that we are parsing it correctly.  Once #559 is merged in we can check the last one off the list and close out.

**Comment by zssherman** [comment]
Finished, closing
