### ISSUE TITLE
read_psl_wind_profiler_temperature not reading full file

### ISSUE THREAD

**Issue by AdamTheisen** [ARM-DOE/ACT#491]
It looks like the new function to read NOAA PSL temperature is not reading the full file.  For instance, the file linked below has 2 times in it 172536 and 175538 UTC but only the first one is being read in.  We need to update it to read in all times in the file.

https://downloads.psl.noaa.gov/psd2/data/realtime/Radar449/WwTempSubHourly/ctd/2022/196/ctd22196.17t

**Comment by mgrover1** [comment]
Thanks for letting me know @AdamTheisen - didn't realize there could be multiple times in a single file. I will get to this this week.
