### ISSUE TITLE
ENH: Enable Hour/Minute Level of Searching with ARMLive API

### ISSUE THREAD

**Issue by mgrover1** [ARM-DOE/ACT#493]
Currently, the hour/minute/second field of the ARM data access API is not being passed to the query, preventing the ability to search at this level. This is an issue when working with larger datasets (ex. x-band radar) where a day of data is 10s of GB in size and a user wants a small subset.

I put together some new logic over in this PR (https://github.com/pangeo-forge/staged-recipes/pull/153) for the Pangeo Forge recipe.

This would be good to bring into ACT + update so users can use more refined searches.

**Comment by AdamTheisen** [comment]
@mgrover1 there is a way to set a time to download a specific file but not files within a specific time range.  Having that option would be useful.

https://github.com/ARM-DOE/ACT/blob/2e598c8f0aec1b36a773f16c65783e01f3fdb7b2/act/discovery/get_armfiles.py#L19

**Comment by mgrover1** [comment]
The question is how do we add this into the API...

Right now, the function takes in `startdate` and `enddate`, which are both strings. We basically have three options:

1. Allow start date and end date to be datetime objects, which allows us to pass seconds directly in there.
```python
startdate = datetime(2022, 7, 19, 12, 0)
enddate = datetime(2022, 7, 19, 14, 0)

data = download_data(...,  startdate, enddate)
```

2. Add a starttime and endtime (formatted as `HHMMSS` as in `time`) field into the function

```python
startdate = "2022-07-09"
starttime = "120000"
enddate = "2022-07-09"
endtime = "140000"

data = download_data(...,  startdate, enddate)
``` 

3. Add additional options to the `date_parser` function to allow seconds as well `(['%Y-%m-%d', '%d.%m.%Y',
                 '%d/%m/%Y', '%Y%m%d', '%Y/%m/%d'])`
```python
startdate = "2022-07-09T12:00:00"
enddate = "2022-07-09T14:00:00"

data = download_data(...,  startdate, enddate)
``` 

And with that last option, we would need to decide which valid strings to accept.

My personal preference would be option 1, since this is more generic + extensible

**Comment by AdamTheisen** [comment]
@mgrover1 I would lean towards option 3 and limit the options mainly because it's less change for the user and sticks with the ARM date convention YYYMMDD.  For all the formats we currently accept (YYYY-MM-DD, DD.MM.YYYY, DD/MM/YYYY, YYYYMMDD or YYYY/MM/DD), could we just add the option to look for 'THHMMSS' onto it?

**Comment by mgrover1** [comment]
We can - so should we support:
* HH:MM:SS
* THH:MM:SS
* HH-MM-SS

Should we just append onto each? Should we allow spaces in between?
ex. DD.MM.YYYYTHH:MM:SS, DD.MM.YYYYTHH:MM:SS

**Comment by AdamTheisen** [comment]
@mgrover1 I think we should try and support what we currently have 

- YYYY-MM-DD
- DD.MM.YYYY
- DD/MM/YYYY
- YYYYMMDD
- YYYY/MM/DD

and then allow the addition of THH:MM:SS onto each.  Would this be feasible?

**Comment by mgrover1** [comment]
Yup! I can submit a PR with that!

**Comment by mgrover1** [comment]
Just trying to think how we would this word this with the doc string/API...
