### ISSUE TITLE
PSL Wind Profile Reader Hardcoded to CTD site

### ISSUE THREAD

**Issue by AdamTheisen** [ARM-DOE/ACT#502]
Line 38 in io.noaapsl.read_psl_wind_profiler is hardcoded to the CTD site, we should automatically read the site code in and parse off of that or update to pass in a site name.

**Comment by AdamTheisen** [comment]
@zssherman would you want to take a stab at this one?

**Comment by zssherman** [comment]
@AdamTheisen Yeah I can take a look!
