### ISSUE TITLE
Add shading keyword to plotting calls.

### ISSUE THREAD

**Issue by kenkehoe** [ARM-DOE/ACT#523]
Matplotlib is changing a default for pcolormesh that should currently be throwing a warning and will eventually be an error for not specifying the "shading" keyword when X and Y coordinate dimensions match data[X, Y] shape.

https://matplotlib.org/stable/gallery/images_contours_and_fields/pcolormesh_grids.html

We should add a keyword of shading='auto' to timeseriesdisplay.py plot() call in a way that can be overwritten by plot() call keyword.

**Comment by zssherman** [comment]
Sounds good! Yeah we had to do something similar in Py-ART if I recall...

**Comment by kenkehoe** [comment]
My mistake, looks like this is already implemented.
