### ISSUE TITLE
Handling Incorrect ARM DQRs when applied with ACT function

### ISSUE THREAD

**Issue by kenkehoe** [ARM-DOE/ACT#530]
We have implemented a function to query the ARM Data Quality Report database to return time periods when data is flagged. There are three levels of flagging within the DQRs, with two of them able to replace the variable values with NaN. ARM has a lot of DQRs where the list of variables is not accurate, and is over listing the affected variables.

For example a DQR may indicate the instrument is malfunctioning and select all variables in the netCDF file. While the data is incorrect the location, time, and QC variables are correct. Currently we loop over variables and apply the DQR to variables listed in the DQR. Some variables listed are scalars which is causing an exception that we catch and handle. Handling the exception has a print statement indicating the scalar variable could not be indexed.

We should discuss a better way to handle these variables as the print statement may confuse users when there is nothing wrong with the scalar variables. A couple of options include:

1) Correctly handling the replacement of data values with NaN for the scalar variables
2) Setting a keyword to enact the print statement, but set to False as default
3) Skip over these most likely incorrectly listed variables.

An example output for sgpaosccn2colaE13.b1 on 20170903 using D170905.3
```
Skipping 'eta_lookup_table' DQR application because of IndexError
Skipping 'base_time' DQR application because of IndexError
Skipping 'alt' DQR application because of IndexError
Skipping 'droplet_size_bounds' DQR application because of IndexError
Skipping 'lon' DQR application because of IndexError
Skipping 'lat' DQR application because of IndexError
```

**Comment by AdamTheisen** [comment]
@kenkehoe I think I have a short fix for this that I wanted to run by you to correctly handle this.

Essentially, if the time range of the data is impacted then we want to flag all values of the scalars or the non-time dimensioned variables right if they are listed in the DQR?

This seems to do just that.  If time's not a dimension in the variable, then flag all the data.  Thoughts?

```
            if 'time' not in ds[var_name].dims:
                ind = np.where((ds[var_name].values == ds[var_name].values) | (np.isnan(ds[var_name].values)))
```

**Comment by kenkehoe** [comment]
I'm not 100% following what you mean by " if the time range of the data is impacted ", since there is no time dimension so I don't know how we make that determination. I guess because of the time range of the file? Overall I think your implementation is correct. I don't think we need to do a np.where. Just make a np.full_like(ds[var_name].values, True) to make the index array.

Do you think we should skip the typically overlisted variable names like lat, lon, alt since the number of incorrect location scalar variables in the ARM program is extremely small? Will cause issues downstream for plotting if we change the location variables to NaN.

**Comment by AdamTheisen** [comment]
@kenkehoe Yes, I was just meaning if the times in the file are in the range of the DQR.  On the full_like, that looks like it would create what we would need in the qc variable and not the indices.  By doing the where, it's integrated into the existing workflow and won't require any additional codes

On lat/lon/alt, would it be better if I set a keyword to skip those?  I am hesitant to make these types of decisions for the user in the event the lat/lon is actually incorrect.

**Comment by kenkehoe** [comment]
OK sounds good. Let's add a keyword as you suggest.
