### ISSUE TITLE
ARM Data API Returns Text when File not Available 

### ISSUE THREAD

**Issue by AdamTheisen** [ARM-DOE/ACT#532]
I tried to download gucceilpblhtM1.a0 but it's not available through the webservice due to it being an a0-level file.  Instead the API returned text that was included in the file.  We should put in a check to ensure that these cases are caught and files are not produced.

```
This data file is not available on /data/archive.  To download this file, please an order via Data Discovery. https://adc.arm.gov/discovery
```

**Comment by zssherman** [comment]
@AdamTheisen So files produced, so you want this instead to catch the warning, warn the user and just return from the function without writing anything?

**Comment by AdamTheisen** [comment]
@zssherman yes, if the data are not available, we wouldn't want to write the files and would instead return the message as an error.  Right now, it just gives the false sense that it's downloading files

**Comment by zssherman** [comment]
Gotcha sounds good

**Comment by zssherman** [comment]
@AdamTheisen I see a return empty list and the warning, not sure where its downloading text still, I can turn it into an error message though and with no return

**Comment by zssherman** [comment]
Nvm yep found it!
