### ISSUE TITLE
Ability to handle time_bounds

### ISSUE THREAD

**Issue by AdamTheisen** [ARM-DOE/ACT#536]
A number of instruments have different methods for averaging to a timestamp, some have the timestamp at the end of the averaging interval and some as the start.  Two examples are the ARM ECOR and EBBR systems at the SGP site and include the time_bounds variable in the dataset. 

It would be beneficial to have a generic function that could update these times to a standard timeframe.  I.e. default to adjusting the times so that it's a standard where the timestamp is at the start of the averaging interval.

**Comment by kenkehoe** [comment]
Yes this would be helpful. ADI has some code to do this I believe. Do we have any suggestions on how to interpolate the data?

**Comment by AdamTheisen** [comment]
@kenkehoe ADI has it in a database but all the information we have should be in the time_bounds variable in the file.  I think we just need to set a standard that we are going to have the sample time mean the start of the averaging period and have a function to adjust the time accordingly.  I.e. like with the EBBR which has a sample time at the end of the averaging period.  I think this is more of an adjustment than an averaging
