### ISSUE TITLE
Utility function to handle tar files

### ISSUE THREAD

**Issue by kenkehoe** [ARM-DOE/ACT#541]
There are times when the data files are delivered in a TAR file. The DQ Office have some utilities for handling TAR data files, including creation of a temporary directory and clean up after the extracted files are used. Would be good to add these utility functions to ACT for others to utilize.

**Comment by zssherman** [comment]
I agree! I know In Py-ART we have functionality for this, let me see if I can dig it up.

**Comment by AdamTheisen** [comment]
@kenkehoe do you think we would put this in the read functions so that if it's a .tar or .tar.gz file, it would call this utility to untar them into a temp directory, read in and then clean up?

**Comment by kenkehoe** [comment]
OK I'll put in read functions. Good idea.

**Comment by kenkehoe** [comment]
In the current PR I have utility functions for creation of TAR and gunzip files, extraction of TAR and gunzip, cleanup of extracted TAR directory and implemented into general reading routine. I assume the functions all exist in Mac, Linux, Windows but we will see with testing.

**Comment by kenkehoe** [comment]
Looks to be an issue with a temporary directory call within a temporary directory call.
