### ISSUE TITLE
Add a PieChartDisplay to Support the Aerosol Community

### ISSUE THREAD

**Issue by mgrover1** [ARM-DOE/ACT#550]
Pie charts are helpful when working with aerosol data. We should have this functionality in ACT.

**Comment by zssherman** [comment]
@mgrover1 Has there been any progress on this?

**Comment by mgrover1** [comment]
Not yet - still working on a prototype

**Comment by AdamTheisen** [comment]
@mgrover1 Is this something that you would want to hand off to Zach or I to work through?  Are there any specific requests from the short course that would be valuable to work in?

**Comment by AdamTheisen** [comment]
Examples from ASR Posters:

https://asr.science.energy.gov/meetings/stm/posters/pdf/2023/P003262.pdf
https://asr.science.energy.gov/meetings/stm/posters/pdf/2023/P003216.pdf
https://asr.science.energy.gov/meetings/stm/posters/pdf/2023/P003240.pdf
https://asr.science.energy.gov/meetings/stm/posters/pdf/2023/P003184.pdf
