### ISSUE TITLE
Accessor not available in dataset

### ISSUE THREAD

**Issue by AdamTheisen** [ARM-DOE/ACT#552]
I fetched the latest updates after the lazy_loading PR and ran pytest and am seeing a lot of errors with accessors not loading.  Clean, QCFilter, and QCTests are no longer available in the datasets for some reason.

FAILED test_io.py::test_io_mfdataset - AttributeError: 'Dataset' object has no attribute 'clean'
FAILED test_io.py::test_io_write - AttributeError: 'Dataset' object has no attribute 'clean'
FAILED test_io.py::test_clean_cf_qc - AttributeError: 'Dataset' object has no attribute 'clean'

**Comment by mgrover1** [comment]
@AdamTheisen can you provide a code snippet to reproduce the error

**Comment by AdamTheisen** [comment]
@mgrover1 see below.  I went to the ACT/act/__init__.py file and added in `from .qc import clean, QCFilter, QCTests` and that fixed the issues I was seeing but not sure that's the right way.

```
import act
sonde_ds = act.io.armfiles.read_netcdf([act.tests.EXAMPLE_MET1])
sonde_ds.clean.cleanup()
```

The other option is to just run pytest test_io.py in the test area
