### ISSUE TITLE
Improve navigating the examples

### ISSUE THREAD

**Issue by kenkehoe** [ARM-DOE/ACT#566]
Currently the examples README.txt  file has a link to the Discussions area. I think the formatting is wrong as the hyperlink returns a 404 error. But I think we should update the README.txt file to more of the heavy lifting to point the user to the correct example than pointing the user to the Discussion area. We may need to rename some of the examples as everything starts with plot_* but not every example generates a plot.

Also, recent PR #563 created a new example to show how to downsample the data before plotting to speed up 2D plotting. I would not know which example to look in to find this information from the name of the file, plot_examples.py. We should create a TOC or some other listing of the problem/example and hyperlink to that example in the examples/README.txt

**Comment by AdamTheisen** [comment]
@kenkehoe that's strange as the link takes me to the discussions page.  I'm not seeing an error.  Can you copy the link and past here that you're seeing?

That is a good point on the examples.  I'm wondering if a FAQ page would be useful so we can explain and point to the examples.  A TOC might get a little long if we try and explain what each example is doing or trying to show.  @mgrover1  any thoughts here?

**Comment by kenkehoe** [comment]
@AdamTheisen  

https://github.com/ARM-DOE/ACT/discussions%3E%60_

**Comment by AdamTheisen** [comment]
I think we figured out that this was related to the actual README in the github repo and not the actual examples page in the documentation.  I think changing the examples README to rst would fix this.

**Comment by mgrover1** [comment]
I would be in favor of adding a more robust user guide, instead of an FAQ section.

**Comment by AdamTheisen** [comment]
@mgrover1 do you know of any examples we could follow for this kind of interface?

**Comment by mgrover1** [comment]
@AdamTheisen - the [MetPy User Guide](https://unidata.github.io/MetPy/latest/userguide/index.html) is really nice! And something similar for ACT would be the best solution I think.

**Comment by AdamTheisen** [comment]
Plan is to categorize the existing examples and then come up with common questions for a How To Guide.

**Comment by mgrover1** [comment]
Let's separate the examples by which module they come from (ex. retrievals)
