### ISSUE TITLE
Speed up Plotting of 2D datasets

### ISSUE THREAD

**Issue by AdamTheisen** [ARM-DOE/ACT#57]
We need to find a way to plot out high-res 2D datasets faster.  The MPL data takes a ridiculous amount of time to plot up 3 plots.  Maybe we need to play around with image plotting of the data as well instead of pcolormesh and see how that works for cases like this.

**Comment by AdamTheisen** [comment]
@rcjackson @scollis Any ideas on how to speed up 2D plotting?  1 day of kazr and 1 day of mpl combined in 2 panel plot took about 5 minutes

**Comment by kenkehoe** [comment]
I had to downsample the data in the object to my plots to render faster. Not sure if we want to do that. Otherwise I have not found any faster plotting options.

**Comment by AdamTheisen** [comment]
Yeah, maybe we just need to note that users should downsample data before plotting if they need a speed increase

**Comment by kenkehoe** [comment]
I have created a PR to speed up the option for plotting with add_nan keyword. Looking at the plotting of radar data I was getting better results by using .resample() method on the Dataset before plotting to get the time step more regular and smaller. The plots looks more correct with non-standard time steps. matplotlib can't render high frequency anyway, should we add keywords to help with resampling down to a more reasonable size? That should help speed up the 2D plotting?

**Comment by AdamTheisen** [comment]
@kenkehoe  coming back to this.  I would have reservations about putting in anything that modifies the data without the user knowing.  I.e. if we defaulted to resample at 1-minute.  I think it is best for the user to resample as they see fit.  Maybe all we really need is to note this in the documentation.  Thoughts?

**Comment by kenkehoe** [comment]
I agree downsampling the data before plotting is not something we should default. I was thinking we could provide some documentation on this issue and a keyword that the user could pass in to perform a downsampling before plotting. That way the user knows the data is downsampled to their desired time/height steps. The default would be no downsampling. Or maybe just providing examples to downsample with xarray is the best option.

**Comment by AdamTheisen** [comment]
I like providing the examples as it's already there in xarray and easy to do in one line of code.  I'll see what I can do
