### ISSUE TITLE
CI: Continuous integration stalls around get_ord testing. Need to pinpoint further

### ISSUE THREAD

**Issue by zssherman** [ARM-DOE/ACT#570]
The CI stalls early on near the get_ord unit tests, no rhyme or reason, happens randomly in one of the test suites (ex: ubuntu 3.7). Need to find a way to skip or rerun if tests take too long.

**Comment by zssherman** [comment]
@AdamTheisen, so it seems testing will randomly hang on the unittest for get_ord. One option i saw is we can add a pytest.mark.timeout to were if the test takes to long it moves on, every PR we tend to get 2-3 of the environments timing out because of the tests and have to rerun it. Trying to think of other options.

**Comment by AdamTheisen** [comment]
@zssherman I have not seen this happen recently have you?  If not, should we close out?

**Comment by zssherman** [comment]
I have not thankfully so maybe something was fixed in their system. We can close this and then if it starts occurring again, can reopen
