### ISSUE TITLE
Add option to include required global attributes when writing to netCDF

### ISSUE THREAD

**Issue by kenkehoe** [ARM-DOE/ACT#591]
Some people are planning to use ACT to generate official datastreams and need to have required global attributes set. We should help them add the correct attributes with correct values.

**Comment by AdamTheisen** [comment]
These are the attributes in question

:command_line = "run Jupyter Notebook workbench" ;
:process_version = "" ;
:history = "created on Jupyter workbench" ;

**Comment by AdamTheisen** [comment]
@kenkehoe  I was thinking about this and I'm not sure we need to force users to set this.  I think an example showing users how they can add these attributes would suffice.  Thoughts?

**Comment by kenkehoe** [comment]
I agree we would not force users to set these global attributes. But we could add some code to help set the variables. Maybe a few method calls to set the values before writing?

**Comment by zssherman** [comment]
I can write up this example. Do we normally set this attributes with system commands or manually input them? And is there an example on what these usually state?
