### ISSUE TITLE
Adding in Additional NEON Info for Clarity

### ISSUE THREAD

**Issue by ajsockol** [ARM-DOE/ACT#593]
I've been working with the ACT code for NEON data recently. For many of the functions, a specific site code and/or product code is needed as argument inputs in order to see what data products are available. I wasn't clear where to get these site codes and product codes, so it might be helpful to add this information in to the NEON example and discovery functions (such as the main NEON site: https://www.neonscience.org/field-sites/explore-field-sites)

**Comment by AdamTheisen** [comment]
@ajsockol check out #596  and if you think that is good for pointing people where to find the NEON site information.

**Comment by ajsockol** [comment]
@AdamTheisen  I think just those couple additional lines of info do the trick!

**Comment by zssherman** [comment]
Closing, added in #596
