### ISSUE TITLE
Ability to check a Dataset against ARM standards to ensure it complies

### ISSUE THREAD

**Issue by AdamTheisen** [ARM-DOE/ACT#597]
There have been some requests for a standards checker of sorts that PI's could use to ensure there data are up to ARM standards.  I want @kenkehoe 's thoughts here as well but I see 2 different checks

1.  Script to check against ARM ingest standards
2. Script to check against an ARM DOD to ensure it matches

The end goal would be to have something that users could easily run against any data product.  I would see this as a io.armfiles code or utils code.  Thoughts?

**Comment by jrobrien91** [comment]
@AdamTheisen Hoping to have something written up for this before AMS. Directly overlaps with corrections I need to make for SAIL CMAC files

I will check with @kenkehoe after getting a draft together to make sure we are handling DOD matching correctly

**Comment by AdamTheisen** [comment]
@jrobrien91 this would be a fairly significant undertaking as we would want it to encompass ARM standards
https://www.arm.gov/publications/programdocs/doe-sc-arm-15-004.pdf

@kenkehoe noted that there's a python script for checking against CF standards that we could potentially adapt.

**Comment by kenkehoe** [comment]
The fastest method right now would be to send me a file or header and I'll review manually. How many PIs are asking for this?

**Comment by zssherman** [comment]
Any update on this one?

**Comment by jrobrien91** [comment]
@zssherman yah this was a bigger undertaking than I anticipated.. next dev meeting let's discuss next steps

**Comment by AdamTheisen** [comment]
@jrobrien91 @zssherman I've been playing around with some ideas.  The one I'm leaning towards is using a cf checker first for base cf standards and then adding on the top 10 or so ARM specific standards.

**Comment by AdamTheisen** [comment]
I just tested another [CF compliance checker](https://github.com/ioos/compliance-checker) that I think will at least take care of the high priority CF standards.  Maybe on top of this, we start with the high-priority ARM standards and tack it on. @kenkehoe I know you're not a big fan of this as a whole but does this sound like a reasonable approach for an ARM standards checker of sorts?

```
import glob
import subprocess
import os
import json

# Define function for printing out from json
def print_priorities(data):

    for p in data:
        if len(p['msgs']) > 0:
            print(p['name'], '\n')
            if isinstance(p['msgs'], list):
                for m in p['msgs']:
                   print(m)
            else:
                print(p['msgs'], '\n')

# Get file location
path = os.getcwd()
file = glob.glob(path + '/*nc')

# Run command line compliance checker
results = subprocess.run(['compliance-checker','--test=cf:1.6', file[0], '-f=json'], stdout=subprocess.PIPE, text=True)

# Read JSON in
data = json.loads(results.stdout)

print('High Priority CF Standards Problems')
prior = data['cf:1.6']['high_priorities']
print_priorities(prior)
```

**Comment by kenkehoe** [comment]
@AdamTheisen  sure we can add this. It will catch 50% of the issues.

**Comment by AdamTheisen** [comment]
After discussions on the ACT call, it was decided that this is not in the scope of ACT and could become significant effort to maintain in the future.  It is best served in a separate repository.
