### ISSUE TITLE
Need to find way to unit test discovery module safely

### ISSUE THREAD

**Issue by rcjackson** [ARM-DOE/ACT#6]
Currently, the discovery module takes in a user specified username and token as a string, but if we want to do unit testing on this module having these hard coded in the unit test is troublesome. Having a more secure way to log into the ARM Archive for testing would enable us to do this unit test safely. 

In addition, due to the size of 2D datasets such as celiometer data, I would like to add a unit test for time-range plots but I need a way to download the celiometer data either from the ARM archive or, for now, downloaded from a temporary location to unit test 2D plotting.

**Comment by scollis** [comment]
Two ways we can do this:
1) Boto has a “fake” mode we could replicate this.
2) work with Giri to make a test account with distributable let’s that has limited access to files 


-sent from a mobile device-

**Comment by AdamTheisen** [comment]
We are saving the test login and token in Travis as a secret token that the discovery module can use in testing.   get_armfiles is currently at 77% coverage so I am closing this out.
