### ISSUE TITLE
Download of CEIL Files from 2017 not forming full files

### ISSUE THREAD

**Issue by AdamTheisen** [ARM-DOE/ACT#601]
When running the following, the files returned are size 0 which is causing issues with the plot_ceil.py example

```
results = act.discovery.download_data(username, token, 'sgpceilC1.b1', '2017-01-14', '2017-01-19')
```

Unknown if it's an ACT or ARM issue.

**Comment by AdamTheisen** [comment]
Same is happening for 2019-01-01 to 2019-01-06 for the plot_multiple_dataset.py example

**Comment by AdamTheisen** [comment]
Incident reported to ARM as well to help with troubleshooting.

**Comment by mgrover1** [comment]
@AdamTheisen is it okay to stick with the 2022 data?

**Comment by AdamTheisen** [comment]
@mgrover1 I think that's fine to stick with 2022. Just want to figure out the issue before closing this to make sure nothing is needed on the ACT side

**Comment by mgrover1** [comment]
Sounds good!

**Comment by AdamTheisen** [comment]
I just verified that this is working and was not an ACT issue.  Closing out.
