### ISSUE TITLE
Colorblind friendly QC Defaults

### ISSUE THREAD

**Issue by AdamTheisen** [ARM-DOE/ACT#604]
The QC plot generation defaults to red/green for incorrect/correct data.  We should really come up with a keyword to pass in to plot a colorblind friendly version or change the default to be colorblind friendly.

**Comment by zssherman** [comment]
I second this, I would say the default, but maybe @kenkehoe can have insight for the data quality folks.

**Comment by kenkehoe** [comment]
I'm happy to update the colors. I think leaving red, yellow, green as default is best since ARM has a long history with those colors. What colors do you suggest?

**Comment by AdamTheisen** [comment]
@kenkehoe I have no experience here but could shifting the green for good to a light blue be an option?  @mgrover1 @zssherman thoughts here?

**Comment by zssherman** [comment]
@AdamTheisen Could try switching out the green red for their equivalents in homeyer or chase spectral as an argument, if its best for maintain the ARM standards as Ken mention.

**Comment by AdamTheisen** [comment]
@zssherman  @kenkehoe  I took some of the RGB values from the Homeyer CMAP function and tested that out. What are your thoughts on this as a cb_friendly keyword.

<img width="1314" alt="image" src="https://user-images.githubusercontent.com/13421074/215193316-d9f4834d-3c0a-4a54-94ea-4a5322d67794.png">

**Comment by zssherman** [comment]
@AdamTheisen Beat me to it! I think having it as an argument would be good for now. But yeah I think this is a good start!

**Comment by AdamTheisen** [comment]
The user can always change the colors themselves with the existing options but this might be a quick method for them to change it.

**Comment by kenkehoe** [comment]
Works for me.

**Comment by AdamTheisen** [comment]
Closing with #613
