### ISSUE TITLE
Error when calling function act.io.armfiles.read_netcdf() from ADI code

### ISSUE THREAD

**Issue by Aifang-Zhou** [ARM-DOE/ACT#618]
When I call the following function to read a sondewnpn.b1 file on JupyterLab:
    sonde_ds = act.io.armfiles.read_netcdf(sondewnpn_file)
It is totally fine and I get the data from the sondewnpn.b1 file.

But when I call the same function in a ADI VAP code, I see the following error:
  sonde_ds = act.io.armfiles.read_netcdf(sondewnpn_file)
  File "/apps/base/python3.6/lib/python3.6/site-packages/act/io/armfiles.py", line 91, in read_netcdf
    ds = xr.open_mfdataset(filenames, **kwargs)
  File "/apps/base/python3.6/lib/python3.6/site-packages/xarray/backends/api.py", line 948, in open_mfdataset
    datasets = [open_(p, **open_kwargs) for p in paths]
  File "/apps/base/python3.6/lib/python3.6/site-packages/xarray/backends/api.py", line 948, in <listcomp>
    datasets = [open_(p, **open_kwargs) for p in paths]
TypeError: open_dataset() got an unexpected keyword argument 'combine_attrs'

Anyone knows the reason? Thanks!

**Comment by Aifang-Zhou** [comment]
@zssherman Thank you for your quick feedback, Sherman!

The xarray array version on ADC server is 0.16.2.

Does that mean I must install the latest xarray version in my conda environment?

Thanks again!

**Comment by AdamTheisen** [comment]
@Aifang-Zhou that xarray version was released in Nov 2020 so I would recommend that you create your own conda environment to run off of.  The python packages installed at a systems level on the ADC systems are usually outdated.  As @zssherman noted, the system python is 3.6 which ACT does not support either.

**Comment by Aifang-Zhou** [comment]
@AdamTheisen Thank you very much for your kind suggestion, Adam! I will do that!

**Comment by zssherman** [comment]
@Aifang-Zhou Were you still running into this issue? If not, do you mind if we close this out?

**Comment by Aifang-Zhou** [comment]
@zssherman The problem is solved by creating conda environment. Please close this thread. Thank you!!
