### ISSUE TITLE
Moving dataset variable names to xarray standards

### ISSUE THREAD

**Issue by zssherman** [ARM-DOE/ACT#619]
After discussion with Matt and Max, we believe we should move all datasets to 'ds' instead of sonde_ds, act_obj etc. Makes its easier on the coding side of things. This would follow as well for dataarrays as 'da' I can take this on. @kenkehoe @AdamTheisen wanted to know your thoughts before I go about this.

**Comment by kenkehoe** [comment]
Fine with me. I'll update the code I'm working on now.

**Comment by AdamTheisen** [comment]
@zssherman that's fine with me as well.  We should be sure to update the contributors guide as well.  This will be somewhat hard to keep track of over time unless we remember to check every PR.  Could we add a PR template with a checkbox for this?

**Comment by zssherman** [comment]
@AdamTheisen Yeah I can give that a try and see if i can put in a template for that.
