### ISSUE TITLE
Attempting to set identical low and high xlims

### ISSUE THREAD

**Issue by kenkehoe** [ARM-DOE/ACT#629]
* ACT version: 1.4.0
* Python version: 3.8.13
* Operating System: Linux

### Description
When processing in an automated queue we sometimes process when there are few time steps. The process does not fail but does produce a warning. 

/.conda/envs/dqo-base/lib/python3.8/site-packages/act/plotting/timeseriesdisplay.py:214: UserWarning: Attempting to set identical low and high xlims makes transformation singular; automatically expanding.

I want to add a check when setting xlim values to ensure start and end are not the same. If so automatically expand the xlim to exclude the warning.

**Comment by zssherman** [comment]
Gotcha that makes sense!
