### ISSUE TITLE
CAPE Calc Problem

### ISSUE THREAD

**Issue by AdamTheisen** [ARM-DOE/ACT#631]
All, I found this conversation and the related #361 when trying to get to the bottom of what would be needed to add the virtual temperature correction to MetPy's CAPE calculations. Unfortunately, I don't think the approach you are using here is correct. The problem comes when you are calling MetPy's `surface_based_cape()` function here: https://github.com/ARM-DOE/ACT/pull/362/files#diff-605c6300a0861a7eaad398f848dd5baa1871d6490dcfcd13224c6f6e9c56d0daL196

While definitely the environmental virtual temperature needs to be used in the calculation, what is happening as near as I can tell is that the `surface_based_cape()` function is internally computing the parcel's *uncorrected* temperature profile and using *that* in the CAPE calculation.  To get the correct CAPE with the virtual temperature correction, the parcel's *virtual* temperature profile needs to be computed as well. Another problem is that, since the environmental virtual temp is being passed in in place of the regular temp, then the starting temperature that is being used internally to compute the parcel profile is using the starting virtual temperature instead, while still using the uncorrected dewpoint. This means that the LCL used internally for the CAPE calculation will be wrong (too high) on top of the parcel profile being incorrectly computed.

_Originally posted by @Meteodan in https://github.com/ARM-DOE/ACT/issues/362#issuecomment-1463033143_

**Comment by AdamTheisen** [comment]
Pulling in @mgrover1 @rcjackson and @zssherman on this one to check out.

**Comment by mgrover1** [comment]
A similar comment was added in my PR upstream to MetPy
https://github.com/Unidata/MetPy/pull/2437

Should this be a higher priority getting this fixed?

**Comment by zssherman** [comment]
@mgrover1 Was there any progress on this on the metpy side of things?

**Comment by mgrover1** [comment]
I have made some progress, with an update provided on the MetPy side https://github.com/Unidata/MetPy/pull/2437#issuecomment-1487599763
