### ISSUE TITLE
Documentation error: ACT Cheat Sheet

### ISSUE THREAD

**Issue by wxwolff** [ARM-DOE/ACT#642]
* ACT version: All
* Python version: 3.9
* Operating System: n/a

### Description

ACT Cheat Sheet (pdf) has typos in install second..

Then install Py-ART:
$ conda install -c conda-forge act_atmos

Should be 

Then install Py-ACT:
$ conda install -c conda-forge act-atmos

### What I Did

Googled "conda act_atmos" which gave correct install command.
```
n/a

```

**Comment by zssherman** [comment]
@wxwolff Good catch! Thanks for bringing that to our attention! I'll get a fix in for that.
