### ISSUE TITLE
Setting y-range for groupby causes error

### ISSUE THREAD

**Issue by AdamTheisen** [ARM-DOE/ACT#648]
* ACT version: 1.4.2
* Python version: 3.10.9
* Operating System: Mac Os

### Description

Trying to set the y-range for a groupby plot creates an error

### What I Did

```
files = glob.glob('./Data/sgpmetE13.b1/*2021*')
files.sort()
obj = act.io.armfiles.read_netcdf(files)
display = act.plotting.TimeSeriesDisplay(obj, subplot_shape=(4, 3))
groupby = display.group_by('month')
groupby.plot_group('plot', None, field='temp_mean', marker=' ')
groupby.display.set_yrng([-20, 50])
plt.show()
```

Error
```
  File "/Users/atheisen/Code/development-space/test_plotting.py", line 26, in <module>
    groupby.display.set_yrng([-20, 50])
  File "/Users/atheisen/Code/ACT/act/plotting/timeseriesdisplay.py", line 267, in set_yrng
    self.axes[subplot_index].set_ylim(yrng)
AttributeError: 'numpy.ndarray' object has no attribute 'set_ylim'
```

**Comment by AdamTheisen** [comment]
Note, I did find a workaround with the groupby object.

```
for ax1 in groupby.display.axes:
    for ax2 in ax1:
        ax2.set_ylim([-30, 50])
```

**Comment by zssherman** [comment]
@AdamTheisen I can take a look at this tomorrow and either implement that as a fix or see what else can be done.

**Comment by zssherman** [comment]
@AdamTheisen I think its due to the two dimensional subplot shape. When applying subplot_index to set_yrng to 0,0 it fixes the problem on my end

**Comment by zssherman** [comment]
But when supplying that, the plot doesn't change however... hmmm

**Comment by zssherman** [comment]
Should we add a groupby parameter like if groupby all subplots change to the yrng or something?
