### ISSUE TITLE
Missing kwargs in plot_stacked_bar_graph

### ISSUE THREAD

**Issue by AdamTheisen** [ARM-DOE/ACT#650]
### Description

I just saw this in the code and wanted to report it.  I think we need to pass in kawrgs to the below line in plot_stacked_bar_graph.

'''
my_hist, bins = np.histogram(xdata.values.flatten(), bins=bins, density=density)
'''

**Comment by zssherman** [comment]
@AdamTheisen Sounds good, I can get a fix in for that

**Comment by zssherman** [comment]
@AdamTheisen Looks like the kwargs are being fed into the axes.step, do we want a **hist_kwargs as well? Values not covered are range and weight

**Comment by AdamTheisen** [comment]
@zssherman that might be helpful or just add the other keywords
