### ISSUE TITLE
act.utils.decode_present_weather classification tables

### ISSUE THREAD

**Issue by mtuftedal** [ARM-DOE/ACT#662]
* ACT version: 1.4.2
* Python version: 3.9.16
* Operating System: Windows 10

### Description

I was working on decoding the FD70 present weather codes for the ATMOS FD70. It appears the FD70 uses both the WMO 4680 and 4677 in the numeric code. For it's metar code it uses WMO 4678. 

When the code encountered a value of 88, for snow pellets, which it adopted from the 4677 table, it errors and stops. Suggestion would possible be adding in some of the WMO4677 to fill number gaps if applicable. 

### What I Did

```
input: 
act.utils.decode_present_weather(ds,variable='present_wx0')
output:

  File D:\anaconda3\lib\site-packages\act\utils\inst_utils.py:133 in <listcomp>
    wx_type = [weather[d] for d in data.values]

KeyError: 88

```

**Comment by mgrover1** [comment]
So I think the best way to approach this be to setup a separate lookup table, and do a join between the two.

For example, 88 is left as unknown in the 4677 standard, is defined in the 4678. When we do a join here, it will update those values without overriding the previous definitions.
