### ISSUE TITLE
Histogram Display Examples

### ISSUE THREAD

**Issue by jrobrien91** [ARM-DOE/ACT#679]
* ACT version: 1.4.5
* Python version: 3.10.8
* Operating System: macOS Ventura 13.3.1

### Description

Within the [histogram display](https://github.com/ARM-DOE/ACT/blob/main/act/plotting/histogramdisplay.py) there are two plotting functions that do not have associated examples within our [Example Gallery](https://arm-doe.github.io/ACT/source/auto_examples/index.html)

These functions are:
- plot_size_distribution
- heat map (though [spatial contour plot](https://arm-doe.github.io/ACT/source/auto_examples/plotting/plot_contour.html#sphx-glr-source-auto-examples-plotting-plot-contour-py) uses this function. Maybe we can add tags to examples for functions used?

**Comment by zssherman** [comment]
I agree that it would be a good first issue. And yeah the heatmap i think would still be a good example as i'm not seeing a standalone use of it.
