### ISSUE TITLE
Standardize discovery module

### ISSUE THREAD

**Issue by AdamTheisen** [ARM-DOE/ACT#688]
We need to standardize the discovery module.  I think it would be better if we remove the "get_" from every file and leave as "neon", "arm", etc...  We then should update the functions to remove "get".

**Comment by zssherman** [comment]
@AdamTheisen So rename the modules and then for those that don't start with download, but instead with get, change those to download_blank as well?

**Comment by AdamTheisen** [comment]
I was also thinking that we might want to follow similar suit to the renaming of HistogramDisplay to DistributionDisplay and copy the codes over to the new name, put in a deprecation warning and then remove in the next major release.

**Comment by zssherman** [comment]
@AdamTheisen Yeah I think that's a good path forward

**Comment by zssherman** [comment]
Deprecation warning i think is a good idea as well to warn people. We could start with one submodule at a time, can change the discover module and have the warning in the original code and then add the duplicates of each module with the renamed file and functions (if functions need renaming).

**Comment by zssherman** [comment]
But I think i get one you mean as well on the function naming, as airnow, its just getting the information from the website and is not actually downloading anything

**Comment by AdamTheisen** [comment]
The base for this is in #724 but we will need to update when we do the V2.0.0 release to remove the old files and make sure the new ones are in __init__.py
