### ISSUE TITLE
Adding plotting options to Skew-T

### ISSUE THREAD

**Issue by cgodine** [ARM-DOE/ACT#699]
Currently the skew-t plotting method has options to include surface-based parcel trace and shading for CAPE and CIN values. MetPy has some additional skew-T plotting features that might be useful:

- `plot_dry_adiabats` - Plots dry adiabat/theta lines
- `plot_mixing_lines` - Plots mixing ratio lines
- `plot_moist_adiabats` - Plots moist adiabats 

Would these be useful to add to the skew-t plotting methods in ACT?

**Comment by zssherman** [comment]
@cgodine I think this would be useful, so essentially just calling Metpy's functionality for these utilizing the ACT xarray dataset format?

**Comment by AdamTheisen** [comment]
I would need to look, could we just pass these as keyword arguments (**kwargs) to the MetPy function?

**Comment by zssherman** [comment]
Yeah that makes sense!

**Comment by cgodine** [comment]
@AdamTheisen from looking at the MetPy documentation for SkewT, it looks like these plotting methods aren't called via kwargs in MetPy but rather as separate plotting methods in the SkewT object in the same manner as plotting the temperature and dew point data ([documentation](https://unidata.github.io/MetPy/latest/api/generated/metpy.plots.SkewT.html#metpy.plots.SkewT.plot_mixing_lines)). I was thinking it would be easiest to add directly to the ACT skew-t plotting method and adding kwargs there.
