### ISSUE TITLE
Epoch addition to ACT Discovery

### ISSUE THREAD

**Issue by jrobrien91** [ARM-DOE/ACT#710]
### Description
One of our current aims for FY24 is to create defined epochs for the SAIL campaign to allow for easier analysis. An addition to the Discovery module to allow users to grab epochs (and associated datastreams) defined within data discovery would be beneficial for outreach and to quick start new projects.

**Comment by zssherman** [comment]
Thanks @jrobrien91, I agree! And @AdamTheisen I'm not seeing in the ARMLive any parameters for the epochs, is this something we have to work with the ADC folks to add as a option parameter in ARM live so we can pull it? Or am I missing it?

**Comment by AdamTheisen** [comment]
@jrobrien91 @zssherman yes, I think this is something that we will have to work with the ADC on.  Let me ping Giri and get his thoughts.

**Comment by zssherman** [comment]
@AdamTheisen Yeah if we have unique ID's I can see how the url looks from data discovery and can add the parameter to the discovery tool

**Comment by AdamTheisen** [comment]
@zssherman I'm wondering if this is an issue we should track for ACT or close out.  Essentially, we need ARM to add this feature to their web service and then we could add it.  Timelines for that happening are unknown.

**Comment by zssherman** [comment]
Lets close this for now and can reopen in the future once its created.
