### ISSUE TITLE
Reorganize the Unit Tests

### ISSUE THREAD

**Issue by AdamTheisen** [ARM-DOE/ACT#731]
@mgrover1 had noted that it would be beneficial to split out the tests and reorganize the test area to make it easier to navigate and so that we don't have extremely long test files for each module.

**Comment by zssherman** [comment]
Agrees!

**Comment by AdamTheisen** [comment]
Just as a note, I started on this but it would be very beneficial to merge in all the changes first and then a release for the new test structure before we get to V2.0.  I don't want to duplicate effort to change all the test functions with what's already changed in the existing PRs.  

Long story short, let's plan to get this in after the V2 PRs are merged but before we do an official V2 release.  @zssherman sound ok?

**Comment by zssherman** [comment]
Yeah that sounds reasonable to me!
