### ISSUE TITLE
Update ARM DQR webservice

### ISSUE THREAD

**Issue by kenkehoe** [ARM-DOE/ACT#733]
### Description

The ARM DQR web-service is changing. Current system uses https://adc.arm.gov/dqrws/ and it is changing to new service  https://dqr-web-service.svcs.arm.gov/docs

### What I Did

I have done nothing yet, but I will update the code to use the new web-service.

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by AdamTheisen** [comment]
@kenkehoe is this a simple change to the url or is the input calls and output data going to be different?

**Comment by kenkehoe** [comment]
The calls and returned object will be different. Also, we can push most/all the filtering to the server. I was planning to work on this update this week.
