### ISSUE TITLE
setup.cfg excluding armfiles.py

### ISSUE THREAD

**Issue by AdamTheisen** [ARM-DOE/ACT#738]
I just noticed in the setup.cfg script, we are excluding act.io.armfiles.py (soon to be arm.py).   We need to figure out if that's still necessary.

**Comment by zssherman** [comment]
Hmm, yeah interesting, can't see why it would be?

**Comment by AdamTheisen** [comment]
It's in the pyproject.toml as well

**Comment by zssherman** [comment]
What I can do is remove it and do a fresh install and see, I'll also dig through the commits to see when and why its was added.

**Comment by zssherman** [comment]
@AdamTheisen Looks to be excluded for flake8 and was added due to a pre-commit change awhile back, I'll take a look and see why its is excluded or if there is PEP8 formatting issues that could have been issues.
