### ISSUE TITLE
ACT HomeyerRainbow cmap not found

### ISSUE THREAD

**Issue by dennyh-ssec** [ARM-DOE/ACT#744]
* ACT version: 1.5.1
* Python version: 3.10.9
* Operating System: ARM Jupyter Hub

I cloned the ARM-Notebooks repository, https://github.com/ARM-Development/ARM-Notebooks, in the ARM Jupyter Hub, https://jupyterhub.arm.gov/, and went to the Tutorials/arm-asr-pi-meeting-2023/ACT_tutorial.

I added "os" to the list of imports and executed. I executed the ACT tutorial showing the first mpl cloud base height plot. Then I went to the end of the tutorial to show an example using AERI data.

At the end end of the tutorial I added a block of code and pasted the aerioe ACT example without the imports, username and token lines.
https://arm-doe.github.io/ACT/source/auto_examples/workflows/plot_aerioe_with_cbh.html#sphx-glr-source-auto-examples-workflows-plot-aerioe-with-cbh-py

It errored out on the HomeyerRainbow cmap. I changed to to a Spectral_r which is fairly close.

**Comment by AdamTheisen** [comment]
@zssherman we probably need to make sure everything is up to date with the ARM-Notebook tutorials in ACT and Py-ART that used the internal colormaps.

**Comment by zssherman** [comment]
@AdamTheisen Agreed, I can take a look in the coming days, sadly out today due to a dental emergency.

**Comment by zssherman** [comment]
@AdamTheisen @dennyh-ssec I submitted a PR to include cmweather in the arm notebooks repo environment.yml, @AdamTheisen do we also need to reach out to the ADC folks to include it in the system environment? I'm not seeing any cmap calls in any of the notebooks themselves.

**Comment by AdamTheisen** [comment]
@zssherman I submitted an INC to request an update to ACT on the ADC JupyterHub systems.  I'll test out again once updated but I was able to recreate the problem.

**Comment by AdamTheisen** [comment]
@dennyh-ssec @zssherman the ADC has updated ACT to version 1.5.3 on the JupyterHub systems.  I tested the example out and it worked so I think we should be good to close this out.  Let us know if you run into any more problems.  Thanks!

**Comment by zssherman** [comment]
Sounds good, thanks @AdamTheisen!
