### ISSUE TITLE
arm_site_location_search - varying output

### ISSUE THREAD

**Issue by sgupta92** [ARM-DOE/ACT#757]
* ACT version: 1.5.3

### Description

sitename='E31'
sitelatlon=act.utils.data_utils.arm_site_location_search(site_code='sgp', facility_code=sitename)
sitelatlon

This seems to return 'sgp E31' but also 'twp E31' at random. Running this part repeatedly does not provide a consistent response.

EDIT: 

I added the following fix for now: 

    sitelatlon=act.utils.data_utils.arm_site_location_search(site_code=sitecode, facility_code=sitename)
    while list(sitelatlon.keys())[0][0:3]!=sitecode:
        sitelatlon=act.utils.data_utils.arm_site_location_search(site_code=sitecode, facility_code=sitename)

Sometimes, this solves the problem. But sometimes, the code runs for a bit before the following error:

HTTPSConnectionPool(host='adc.arm.gov', port=443): Max retries exceeded with url: /elastic/metadata/_search (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000023C2A4FC610>, 'Connection to adc.arm.gov timed out. (connect timeout=None)'))

**Comment by zssherman** [comment]
@sgupta92 Hmm yeah that's odd, thanks for the heads up! I'll look into why it is returning as such

**Comment by zssherman** [comment]
@sgupta92 I think I found a fix, I had a missing space in the query string so sgp was being combined with 'AND' and I think the search was then just finding facilities and not correctly finding the site

**Comment by sgupta92** [comment]
@zssherman Ran the code after making this change. Works like a charm. Thanks!

**Comment by zssherman** [comment]
@sgupta92 Perfect thanks for raising the issue and testing it out!

**Comment by zssherman** [comment]
Fixed in #758 closing
