### ISSUE TITLE
Verify that unit tests for plotting are comparing and doing what it's supposed to.

### ISSUE THREAD

**Issue by AdamTheisen** [ARM-DOE/ACT#768]
There have always been quirks with the image tests, especially when running on GitHub CI.  Need to perform some baseline testing to ensure it's appropriately comparing plots with the baseline images.  It would also be good to understand what changes to the plots will fall within the threshold for differences and if we should adjust those thresholds.

**Comment by AdamTheisen** [comment]
I've done some testing of the pytest mpl image_compare thresholding on what passes/fails the tests and the results are interesting.  The default mpl tolerance is 2 whereas many of the ACT tests have a tolerance of 30 which can lead to large changes in the plots going undetected.  Attached is a PDF of the results of the different tests along with a spreadsheet of those results.  At a base level, a lot of the changes I implemented, while changing the plots would not have failed our tolerance of 30.

[ACT_plot_testing_data.xlsx](https://github.com/ARM-DOE/ACT/files/14251116/ACT_plot_testing_data.xlsx)

[ACT_plot_testing.pdf](https://github.com/ARM-DOE/ACT/files/14251115/ACT_plot_testing.pdf)

@mgrover1 @zssherman @kenkehoe at a base level, I would recommend that we change our tolerance to 10 so we can address any changes in our plot functions.  We can address the tests that are failing on an individual basis to determine if we should increase that tolerance.  Thoughts?

**Comment by AdamTheisen** [comment]
Quick and easy plot of the RMS values for each test. 
<img width="658" alt="image" src="https://github.com/ARM-DOE/ACT/assets/13421074/d71607bf-f65f-4f15-8712-71b61f9a89e4">

**Comment by kenkehoe** [comment]
OK a value of 10 sounds reasonable. Do you know how that value will be accepted by the different operating system tests?

**Comment by mgrover1** [comment]
That sounds reasonable - I think the key reason why we see these differences is that we are using defaults with many of the packages, and those change when updates are applied to matplotlib, etc. 

One way around this would be to add additional configuration defaults, limiting where we see these differences, or pinning specific versions of packages within our CI to see where things change. Honestly, I do not think it is a huge issue, and using 10 sounds reasonable.

**Comment by AdamTheisen** [comment]
Sounds good!  I can work on this and then we can address the problem ones when they arise
