### ISSUE TITLE
Rename CSV submodule

### ISSUE THREAD

**Issue by mgrover1** [ARM-DOE/ACT#787]
* ACT version: 2.0
* Python version: All
* Operating System: All

### Description

We should consider renaming the `act.io.csv` submodule in ACT. It will lead to import issues with pandas, as it is not recommended to have modules titled `csv`

[see the thread here](https://stackoverflow.com/questions/60912657/python-pandas-cannot-import-quote-minimal)

We can still keep the same API - `read_csv`, but we should rename to something like "text" or "tabular". Thoughts?

### What I Did

Upon submitting a PR, the following error appeared:

```python
ImportError: cannot import name 'QUOTE_NONNUMERIC' from partially initialized module 'csv' (most likely due to a circular import) (/Users/jrobrien/dev/ACT/act/io/csv.py)
```

**Comment by zssherman** [comment]
@mgrover1 I would be fine with that, we would just need to reach out to the DQ folks etc. It should not change the import path if act.io.read_csv is used, but i know sometimes act.io.csv. has been used. So would have to make sure it doesn't break anything. I post in the act channel

**Comment by AdamTheisen** [comment]
I would be okay changing it to act.io.text since it really can do more than just csv

**Comment by mgrover1** [comment]
I agree here @AdamTheisen !! I can draft up a PR.

**Comment by zssherman** [comment]
@AdamTheisen @mgrover1 Sounds good! I say yeah, submit the PR and we'll greenlight once we get the ok from the DQ folks

**Comment by rcjackson** [comment]
> PySP2 will need an update as well here (cc @rcjackson )

Just let me know what is decided for the new name then I can push a micro-release.

**Comment by mgrover1** [comment]
`act.io.text` is the decision based on the conversation in this thread

**Comment by zssherman** [comment]
@mgrover1 Can't we drop the second reference as we're importing read_csv in the init?
