### ISSUE TITLE
Add warning to change units when fails

### ISSUE THREAD

**Issue by kenkehoe** [ARM-DOE/ACT#793]
Need to add warning to change units method to indicate when a problem occurs, but don't raise an error as many string units are not correct or udunits compliant.

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by zssherman** [comment]
@kenkehoe Makes sense to me!
