### ISSUE TITLE
ACT Documentation Updates

### ISSUE THREAD

**Issue by AdamTheisen** [ARM-DOE/ACT#829]
There was a user question about some of the ACT documentation.  In the [User Guide](https://arm-doe.github.io/ACT/userguide/usage.html), towards the bottom on downloading data from the ARM archive, it notes that they need a username and token.  We should further elaborate on what those are and how to get them.  Also, need to just say "download data from ARM" (cutting our archive).

**Comment by zssherman** [comment]
@AdamTheisen Did you have the webpage for creating a username etc? (was having trouble finding it). I was going to go through it and add it to the documentation.

**Comment by AdamTheisen** [comment]
@zssherman  here's the one for the token: https://adc.arm.gov/armlive/ and for the username, this is the registration form: https://adc.arm.gov/armuserreg/#/new
