### ISSUE TITLE
GeographicPlotDisplay documentation missing description of return value

### ISSUE THREAD

**Issue by rcjackson** [ARM-DOE/ACT#833]
* ACT version:  2.1.1
* Python version: all
* Operating System: all

### Description

The GeographicPlotDisplay is missing a description of the returned matplotlib axes object. This proved to be a bit confusing on how to tell a student how to adjust the axes limits on the GeographicPlotDisplay, since doing so depends on calling the methods of the returned matplotlib axes object.

**Comment by zssherman** [comment]
@rcjackson Thanks for the heads up, I will work on a change for it! Wait nevermind I see you self assigned

**Comment by rcjackson** [comment]
@zssherman feel free to work on the quick fix if you have time

**Comment by zssherman** [comment]
@rcjackson I do, will work on that now!

**Comment by zssherman** [comment]
@rcjackson For clarification, so a return doc statement for the class itself or one of the plotting functions is missing it? Most of our classes in Py-ART and ACT don't have return docs, so trying to understand

**Comment by zssherman** [comment]
I do see geoplot is missing a return
