### ISSUE TITLE
Feature Request: QC function to summarize the QC

### ISSUE THREAD

**Issue by AdamTheisen** [ARM-DOE/ACT#843]
It would be beneficial to add in a function that summarizes the QC in an object (0=good, 1=indeterminate, 2=Bad)...

**Comment by AdamTheisen** [comment]
@ michaeltg12 Pinging you here for awareness

**Comment by AdamTheisen** [comment]
@michaeltg12 finally was able to get you in here.

**Comment by michaeltg12** [comment]
Thank you very much @AdamTheisen . I'm glad to be involved.
