### ISSUE TITLE
Pytest expecting test to return None

### ISSUE THREAD

**Issue by kenkehoe** [ARM-DOE/ACT#875]
Since pytest version 7.2 tests are expected to return None. If the test returns something else a warning is raised. We return plots instead of None for many of our plotting tests. 

This is raising over 200 warnings when running Pytest. We should look into a way to not trigger so many warnings.

**Comment by zssherman** [comment]
@kenkehoe Any luck with pytest-mpl being installed?

**Comment by kenkehoe** [comment]
@zssherman yes I installed and did not get the warnings. We have a lot of other warnings. I will take a look and see if i can reduce some so we are actually keeping up to date on things.

**Comment by kenkehoe** [comment]
Closing.
